- app/Http/Controllers/UserController.php
- resources/views/user/stats.blade.php
時間帯(0～23時)、および曜日別のチェックイン回数グラフを追加。
> 時間帯・曜日別チェックイン回数グラフ

- app/Http/Controllers/EjaculationController.php
- composer.json
- composer.lock
- database/migrations/2019_01_13_224305_change_link_on_ejaculations.php
refs #15
だいたい2100文字程度が上限と言われているし、4000文字あれば足りるっしょ！！
> オカズリンクの上限を2000文字に拡張

- Dockerfile
- README.md
> #17 開発環境の構築に関するメモを追加

- resources/views/layouts/base.blade.php
> ドロップダウンにプロフィールへのリンクを追加

- app/MetadataResolver/DLsiteResolver.php
> 不要なインポートの削除

- app/MetadataResolver/DLsiteResolver.php
- app/MetadataResolver/MetadataResolver.php
- app/MetadataResolver/PixivResolver.php
R-18作品と漫画のページ指定で画像が取得できるようになります。
> PixivResolverの追加

- app/Http/Controllers/EjaculationController.php
> チェックイン修正時のバリデーションエラーで新規作成に飛ばされてしまうバグの修正

- README.md
- app/Http/Controllers/EjaculationController.php
https://mstdn.maud.io/@owatan/101427053859030415
https://stellaria.network/@Eai/101431376430945318
https://mstdn.maud.io/@yomi/101431454316839212
> Linux環境で権限がないためファイルを書き込めない問題を修正

- README.md
- docker-compose.debug.yml
DBを見るために毎回 `docker-compose.yml` を書き換えていたのでデバックモードを追加しました。
> docker-compose.debug.ymlを追加

- .php_cs.dist
> php-cs-fixer のルールに single_quote を追加

- app/Http/Controllers/SettingController.php
- resources/views/layouts/base.blade.php
- resources/views/setting/base.blade.php
- resources/views/setting/privacy.blade.php
- resources/views/setting/profile.blade.php
- routes/web.php
とりあえず最低限。
パスワード変更とか追々追加していきましょ。
> ユーザー設定画面 (プロフィール, プライバシー関連)

- resources/views/search/index.blade.php
- resources/views/user/profile.blade.php
> チェックイン要素の全体にword-wrapを設定

- app/MetadataResolver/OGPResolver.php
- tests/Unit/MetadataResolver/OGPResolverTest.php
> OGPからタイトル情報が取れない場合はtitleタグから取得を試みる

- app/MetadataResolver/KomifloResolver.php
> Release 20190123.0045

- app/Http/Controllers/UserController.php
> 月間グラフの表示範囲が月末になると1ヶ月ズレるバグの修正

- resources/views/ejaculation/checkin.blade.php
- resources/views/ejaculation/edit.blade.php
> タグ入力欄の高さが自動で拡張されるよう修正

- app/Http/Middleware/RedirectIfAuthenticated.php
> ログイン済の状態でログインページ等にアクセスした際のリダイレクト先が間違っていたので修正

- app/MetadataResolver/MetadataResolver.php
- app/MetadataResolver/NarouResolver.php
Cookie設定のためだけのResolverです。
`description` 用にあらすじでも取ろうかと思ったけど、そんなに短くなさそうなのでやめておきました。(そもそもサイトを利用したことがないので勝手が分からない……)
refs #70
> NarouResolverを追加

- app/Http/Controllers/SearchController.php
> 検索画面のページネーションURLに検索クエリが含まれるよう修正

- resources/views/guest.blade.php
- resources/views/home.blade.php
- resources/views/info/index.blade.php
- resources/views/info/show.blade.php
> お知らせがpinnedの場合ピン留めの表示をする

- resources/views/layouts/base.blade.php
深く考えずにPRしているので、意図的なものであればさくっとcloseしていただければ。
> 著作権表示の年を更新

- app/MetadataResolver/OGPResolver.php
- tests/Unit/MetadataResolver/OGPResolverTest.php
例えば🐯でサークル名とか作者名とかがdescriptionに入ってくれてよいのではって感じです。
> OGPResolverでmeta[name="description"] にフォールバックする

- public/css/tissue.css
- resources/views/layouts/base.blade.php
Tissueを利用するためには、ブラウザのJavaScriptが有効であることを暗黙の前提としていました。  
#78 の機能実装によって、JavaScriptが無効な環境だと何も出てこない可能性が出てきてしまったので、メッセージを出すようにしました。
ログイン済の場合は何も出ないということは無いのですが、必要なものは必要なので。
> ブラウザ設定でJavaScriptが無効になっている場合、メッセージを表示

- app/Http/Controllers/HomeController.php
> トップページに表示されるグラフが少なすぎるバグの修正

- app/MetadataResolver/CienResolver.php
- app/MetadataResolver/MetadataResolver.php
[#57](https://github.com/shikorism/tissue/issues/57#issuecomment-462789238) での調査を基に、メタデータを失効させるためのリゾルバです。
> CienResolver

- app/Http/Controllers/HomeController.php
- app/MetadataResolver/CienResolver.php
- app/MetadataResolver/MetadataResolver.php
> Release 20190216.0130

- app/MetadataResolver/PixivResolver.php
すいません 🙇 
Ref: https://shikorism.net/checkin/1209
> Pixivのリンクにpageが含まれていても画像URLに反映されていない問題を修正

- public/css/tissue.css
> CSSプロパティのtypoを修正

- resources/views/components/profile-stats.blade.php
> 概況の通算回数をnumber_formatでフォーマット

- app/Http/Controllers/Api/CardController.php
- app/Http/Controllers/UserController.php
- routes/api.php
- routes/web.php
`artisan route:cache` できるようにする。
> ルーターにコールバックで直接登録されてるルートをコントローラーに移動

- app/MetadataResolver/KomifloResolver.php
@hinaloe が見つけてくれたt.komiflo.comを使ってサムネイルを取得するPRです。
https://mstdn.maud.io/@hina/101624836249083044
現在このブランチを https://tissue-testing.mizle.net/user/eai でテスト運用中です。
問題が起きないかしばらく様子を見てからマージしたいと考えてます。
（シグネチャや有効期限などはなさそうなので大丈夫だとおもいますが……）
Ref: #30
> KomifloResolverに画像の取得をまた追加

- app/MetadataResolver/MetadataResolver.php
ちゃんと目が通せてないので他にも見落としがあるかもしれない
fix #110
> コンテナ使っていないコンストラクタが残ってた fix #110

- app/Http/Kernel.php
- app/Http/Middleware/TrustProxies.php
5.4 → 5.5 アップグレードの時に入れ忘れていたみたいなので。
> laravel/laravel:5.5からTrustProxiesを輸入

- .circleci/config.yml
CircleCIの設定ファイルを書いた。とはいえ全く使ったことがないので、サインアップした後に出てきたサンプル的なやつを少し書き換えただけ。
php-cs-fixerの呼び出しをdry-runに留めたのは単に自分の趣味。
fix #116
> CircleCIの設定ファイルを追加

- app/Http/Controllers/TimelineController.php
- resources/views/home.blade.php
- resources/views/timeline/public.blade.php
- routes/web.php
お惣菜をたくさん漁れる画面を実装しました。
↑ ページネーション対応です。
close #123
> お惣菜コーナーをもっとたくさん見る画面

- app/MetadataResolver/FanzaResolver.php
なぜか`<br>`などが`<>`になって残っているのでそれを削除します。
本当に<>があった場合も消えそうな気がするけどおそらく問題ないでしょう。（適当）
> FanzaResolverでdescriptionにある不要な`<>`を削除する

- .gitignore
> /.vscodeを.gitignoreに追加

- README.md
- package.json
- resources/assets/sass/tissue.css
- resources/views/ejaculation/show.blade.php
- resources/views/home.blade.php
- resources/views/search/index.blade.php
- resources/views/timeline/public.blade.php
- resources/views/user/profile.blade.php
- yarn.lock
Bootstrap 4.3.0のアップデート項目はこちら
https://blog.getbootstrap.com/2019/02/11/bootstrap-4-3-0/
> Bootstrap 4.3.1にアップデート

- .circleci/config.yml
- package.json
- yarn.lock
CSSのプロパティがいい感じにソートされたら嬉しい！
CIのやつにも追加する必要がありそうです しました
❌付いてるのは既存のCSSをlintしてないからで、mergeする直前に`yarn run stylelint --fix`してください（その間にCSSに変更があるとコンフリクトの解決がめんどくさそうなので）
> Stylelintを導入する

- package.json
なんかCIがコケてるなぁと思ったら、globパターン違うみたいですね…？
> stylelintの対象ファイルパターンを修正

- resources/assets/js/app.js
> アラートの自動削除を削除

- resources/views/search/index.blade.php
> タグ検索結果から編集・削除ボタンを消す

- app/MetadataResolver/FC2ContentsResolver.php
- app/MetadataResolver/MetadataResolver.php
- tests/Unit/MetadataResolver/FC2ContentsResolverTest.php
- tests/fixture/FC2Contents/adult.html
- tests/fixture/FC2Contents/general.html
[FC2コンテンツマーケット](https://contents.fc2.com/)に対応する`FC2ContentsResolver`を追加します。
> FC2ContentsResolverを追加

- Dockerfile
- README.md
fix #130 
とりあえずwebコンテナにnodeを同居させる形を取った。同居させる必要性はそこまでなくて素のnodeコンテナを別に用意してもいいと思うがコマンドの一貫性ということで。
またREADMEにアセット周りの草案を追加しています。よしなにしてください。
> Dockerにnodeを追加する

- app/MetadataResolver/MelonbooksResolver.php
定型文を削除します。
サークルによるコメントが有る場合は説明欄に追記します。
改行文字を使用しているため、使用する場合は #87 の対処が必要です。
> MelonbooksResolverで余分な説明文を削除・整形する

- resources/views/setting/profile.blade.php
> プロフィール設定にアイコンプレビューと登録メールアドレスの欄を追加する

- README.md
- composer.json
わからないひともいるかも知れない（わたしです）
そろそろ CONTRIBUTING.md に分けるべきかもしれない。
> READMEに phpunit の使い方を追記

- app/MetadataResolver/MetadataResolver.php
> ToranoanaResolverのマッチ対象に電子書籍と女性向け通販を追加

- resources/assets/js/checkin.js
> Release 20190421.1742

- app/MetadataResolver/MetadataResolver.php
> DLsiteResolverの正規表現を修正

- package.json
- resources/assets/js/checkin.ts
- resources/assets/js/components/TagInput.vue
- resources/assets/js/vue-shims.d.ts
- resources/views/ejaculation/checkin.blade.php
- resources/views/ejaculation/edit.blade.php
- tsconfig.json
- webpack.mix.js
- yarn.lock
jQueryでしょーーーもないXSS産んだりする (91c786199ac44b118a6108d5f70f8b2556b8036e) のは悲しくなってしまうし、今後より手の込んだフォームにするには今のうちにjQueryやめておいたほうが良いだろうという考えで、Vue.jsの導入を検討します。
あとついでにTypeScriptも入れちゃえ
* tsconfigは無難かどうか (希望として、あまり緩くてもTS入れる意味がないのでstrictな感じにはしたい)
* タグ入力欄に質の良いライブラリコンポーネントを使うとかそういう検討
> タグ入力欄のVue化

- app/MetadataResolver/MetadataResolver.php
- app/MetadataResolver/PixivResolver.php
fix #195
なんかajaxで使うようにいい感じのAPIがあったのでそれを使ったらいい感じになった気がします。
> PixivResolverの修正（2戦目）

- composer.json
> composer fixでconfigを指定する

- app/MetadataResolver/DLsiteResolver.php
- app/MetadataResolver/MetadataResolver.php
> DLsiteResolverで予告作品に対応

- .stylelintignore
> .stylelintignoreを追加

- .circleci/config.yml
- Dockerfile
新しい機能を追加するとテストを放置しがち。カバレッジは高いほうが嬉しいのでPR毎に変化を知らせてくれるのは有益だとお思います。
Codecov Appをリポジトリに追加した場合、PRはこのようになります: https://github.com/eai04191/tissue/pull/16
> codecovを追加する

- tests/Unit/MetadataResolver/KomifloResolverTest.php
- tests/fixture/Komiflo/comic.json
- tests/fixture/Komiflo/comicWithNoParents.json
> KomifloResolverのテストを追加

- tests/Unit/MetadataResolver/CreateMockedResolver.php
- tests/Unit/MetadataResolver/DLsiteResolverTest.php
- tests/Unit/MetadataResolver/FC2ContentsResolverTest.php
- tests/Unit/MetadataResolver/KomifloResolverTest.php
- tests/Unit/MetadataResolver/NijieResolverTest.php
- tests/Unit/MetadataResolver/PixivResolverTest.php
- tests/Unit/MetadataResolver/PlurkResolverTest.php
> Lint tests

- Dockerfile
- README.md
いきなり入れておいてもあまり問題ないんじゃないかと思うんですが、何か問題があったら教えてください。
fix #221
> prestissimoのインストールをDockerfileに含める

- .circleci/config.yml
- phpunit.xml
> 定期的に実際のリクエストを伴うMetadataResolverのテストを実行する

- app/MetadataResolver/DLsiteResolver.php
- tests/Unit/MetadataResolver/DLsiteResolverTest.php
- tests/fixture/DLsite/testHTMLdescription.html
> DLsiteResolverのdescriptionをstrip_tagsに通す

- app/MetadataResolver/IwaraResolver.php
- app/MetadataResolver/MetadataResolver.php
- tests/Unit/MetadataResolver/IwaraResolverTest.php
- tests/fixture/Iwara/images.html
- tests/fixture/Iwara/video.html
- tests/fixture/Iwara/youtube.html
- ~~[ ] vimeo対応~~
- ~~[ ] GoogleDrive対応~~
> IwaraResolver 拡張など

- composer.lock
- yarn.lock
> Package update (20190904)

- tests/Unit/MetadataResolver/ToranoanaResolverTest.php
- tests/fixture/Toranoana/testJoshi.html
- tests/fixture/Toranoana/testJoshiD.html
- tests/fixture/Toranoana/testJoshiR.html
- tests/fixture/Toranoana/testJoshiRD.html
- tests/fixture/Toranoana/testTora.html
- tests/fixture/Toranoana/testToraD.html
- tests/fixture/Toranoana/testToraR.html
- tests/fixture/Toranoana/testToraRD.html
> ToranoanaResolverのfixture・テストを更新

- tests/Unit/MetadataResolver/DLsiteResolverTest.php
- tests/fixture/DLsite/testBL.html
- tests/fixture/DLsite/testBooks.html
- tests/fixture/DLsite/testComic.html
- tests/fixture/DLsite/testEcchiEng.html
- tests/fixture/DLsite/testEng.html
- tests/fixture/DLsite/testGirls.html
- tests/fixture/DLsite/testGirlsPro.html
- tests/fixture/DLsite/testHTMLdescription.html
- tests/fixture/DLsite/testHome.html
- tests/fixture/DLsite/testManiax.html
- tests/fixture/DLsite/testPro.html
- tests/fixture/DLsite/testSoft.html
> DLsiteResolverのfixture・テストを更新

- app/MetadataResolver/CienResolver.php
- app/MetadataResolver/DLsiteResolver.php
- app/MetadataResolver/FC2ContentsResolver.php
- app/MetadataResolver/FantiaResolver.php
- app/MetadataResolver/FanzaResolver.php
- app/MetadataResolver/IwaraResolver.php
- app/MetadataResolver/KomifloResolver.php
- app/MetadataResolver/MelonbooksResolver.php
- app/MetadataResolver/NarouResolver.php
- app/MetadataResolver/NijieResolver.php
- app/MetadataResolver/OGPResolver.php
- app/MetadataResolver/PatreonResolver.php
- app/MetadataResolver/PixivResolver.php
- app/MetadataResolver/PlurkResolver.php
- app/MetadataResolver/SteamResolver.php
- app/MetadataResolver/ToranoanaResolver.php
- tests/Unit/MetadataResolver/CreateMockedResolver.php
- tests/Unit/MetadataResolver/OGPResolverTest.php
ref: c0b76e5
DeviantArtResolverとNicoSeigaResolverはノータッチです。
> 不要な成否判定の削除

- app/Ejaculation.php
> いいね非公開のユーザーが、チェックイン画面のいいね件数欄に露出してしまう不具合の修正

- resources/views/auth/register.blade.php
- resources/views/setting/profile.blade.php
ユーザー名を変更可能にするつもりはないので、新規登録画面と設定画面にはそのように記載することにした。
> ユーザー名は変更できないことを明記する

- app/MetadataResolver/Kb10uyShortStoryServerResolver.php
- app/MetadataResolver/MetadataResolver.php
- tests/Unit/MetadataResolver/Kb10uyShortStoryServerResolverTest.php
- tests/fixture/Kb10uyShortStoryServer/tomone.html
自分のサービスの Resolver を追加するデベロッパーの鑑
* `Kb10uyShortStoryServerResolver` と、対応するテストを追加しました。
* 作品ページのみ対応しています。
> Kb10uyShortStoryServerResolver の追加

- resources/assets/js/app.js
ここでログインページに投げてもいいんだけど、投げてかつここに戻らせる方法が分からないので促すだけにした。
作りこみ無しで、標準であったりしないですかね……(ドキュメント読み不足)
refs #279
> 非ログイン状態でいいねしようとした時にログインを促す

- app/MetadataResolver/XtubeResolver.php
- tests/fixture/Xtube/video.html
- サムネイルの取得方法を変更
- tagの各要素をtrimする
> XtubeResolver 修正

- resources/views/layouts/base.blade.php
モバイルで表示されて嬉しいかというと、割とどうでもいいのですが。
> 管理画面へのリンクがモバイルで表示されないバグの修正

- app/MetadataResolver/HentaiFoundryResolver.php
- app/MetadataResolver/MetadataResolver.php
- composer.json
- composer.lock
- tests/Unit/MetadataResolver/HentaiFoundryResolverTest.php
- tests/fixture/HentaiFoundry/illust.html
アダルトイラストサイトHentaiFoundryに対応します。
PECLとかよくわからなかったのでComposerでhttp_build_urlのサポートをするライブラリを入れました。問題があれば教えて下さい。
https://github.com/jakeasmith/http_build_url
> HentaiFoundryResolverを追加

- resources/assets/js/user/stats.js
> 月間チェックイン回数グラフの期間セレクターが、直近1年の範囲しか選択できないバグを修正

- resources/assets/js/user/stats.js
> Release 20191226.0000

- app/MetadataResolver/DLsiteResolver.php
- tests/Unit/MetadataResolver/DLsiteResolverTest.php
- tests/fixture/DLsite/testBL.html
- tests/fixture/DLsite/testBooks.html
- tests/fixture/DLsite/testComic.html
- tests/fixture/DLsite/testEcchiEng.html
- tests/fixture/DLsite/testEng.html
- tests/fixture/DLsite/testGirls.html
- tests/fixture/DLsite/testGirlsPro.html
- tests/fixture/DLsite/testHTMLdescription.html
- tests/fixture/DLsite/testHome.html
- tests/fixture/DLsite/testManiax.html
- tests/fixture/DLsite/testPro.html
- tests/fixture/DLsite/testSoft.html
フォローボタン`.btn_follow`を動的作成するようになったためエラーが出ていたので、削除クラス名を`.add_follow`に変更しました
ついでにfixtureを更新しました
> DLsiteResolver の修正と更新

- resources/assets/js/components/TagInput.vue
> タグの入力確定時にtrimする

- app/Utilities/Formatter.php
- resources/views/components/ejaculation.blade.php
- resources/views/components/profile.blade.php
- resources/views/ejaculation/show.blade.php
- resources/views/home.blade.php
- resources/views/layouts/base.blade.php
- resources/views/setting/profile.blade.php
- resources/views/user/profile.blade.php
- tests/Unit/Utilities/FormatterTest.php
srcset文字列をいい感じに生成するヘルパーメソッドを追加し、各Viewで使用しました。
fix #318
> プロフィール画像のsrcsetを出力するヘルパーを追加

- app/MetadataResolver/MetadataResolver.php
`ci-en.dlsite.com` を捕捉できるようにしました。
fix #323
> Ci-enのドメインが変わっていたのでパターンに追加

- app/Http/Controllers/Api/CardController.php
- app/Listeners/LinkCollector.php
- app/Services/MetadataResolveService.php
Event listenerとControllerで二重に実装されていたので統一したのですが、Modelのstaticでもいいんじゃねとかすごく悩んでいます。
> メタデータの解決と保存の処理を統一

- app/Tag.php
> Tag -> Metadata のリレーション設定

- database/migrations/2020_05_16_165243_make_primary_key_on_metadata.php
- database/migrations/2020_05_16_165705_add_unique_constraint_to_tags.php
本来そうあるべきなんですが、どうして……
refs #330
> metadata.urlをPKに、tags.nameをUNIQUEに設定

- app/Tag.php
- database/migrations/2020_05_16_165243_make_primary_key_on_metadata.php
- database/migrations/2020_05_16_165705_add_unique_constraint_to_tags.php
> Release 20200516.1708

- app/Http/Controllers/SettingController.php
- app/Services/CheckinCsvExporter.php
- resources/views/setting/base.blade.php
- resources/views/setting/export.blade.php
- routes/web.php
> チェックインデータのエクスポート

- app/Services/CheckinCsvExporter.php
> CSVエクスポートの日付書式が仕様と違っていた

- app/Http/Controllers/HomeController.php
- app/Http/Controllers/TimelineController.php
> 未来のオカズはお惣菜として出さない

- app/Ejaculation.php
- app/Http/Controllers/EjaculationController.php
- database/factories/EjaculationFactory.php
- database/migrations/2020_05_24_193301_make_non_nullable_source_on_ejaculations.php
- tests/Feature/SettingTest.php
Eloquentで書いてなんか上手くいかなかったので生クエリにしたんですが、方法あったら誰か教えてください。
> ejaculations.sourceはNULL非許容にする

- app/Http/Controllers/EjaculationController.php
- resources/views/ejaculation/checkin.blade.php
- resources/views/ejaculation/tools.blade.php
- routes/web.php
fix #302 
@unarist に提案していただいた文章をそのまま使いました。(変更必要そうだったら連絡ください)
> ブックマークレット等の案内ページ

- resources/views/user/profile.blade.php
> Release 20200524.2144

- resources/views/components/ejaculation.blade.php
今までずっと壊れてたのかすら分からないが、なんでこれで今までやってきてたんだ……？？？
> チェックインのユーザーリンクのパラメータ名がおかしいのを修正

- resources/views/user/profile.blade.php
> Release 20200524.2244

- app/Http/Controllers/Admin/InfoController.php
- resources/views/admin/info/index.blade.php
> Release 20200525.0123

- .circleci/config.yml
- app/Providers/AppServiceProvider.php
正しいクローラーであるようにしたと言いたいですが、実際にはTwitter対策です。
> 外部へのHTTPリクエストに独自のUser-Agentを付与する

- .github/dependabot.yml
依存パッケージちゃんと管理しよう
see
- https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
- https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem
> dependabotのセットアップ

- resources/lang/ja/auth.php
ログインエラー時のメッセージが翻訳されていないのがなんか気になってきたので追加？
> auth言語ファイルの追加

- package.json
> [fix] lint-staged のglobパターンが誤ってた

- app/MetadataResolver/FanzaResolver.php
> FANZA: 年齢認証Cookieを送信する

- app/Http/Controllers/Api/CardController.php
- app/Listeners/LinkCollector.php
- app/MetadataResolver/DeniedHostException.php
- app/Services/MetadataResolveService.php
> Tissue内のURLに対するメタデータ取得は拒否する

- app/Services/MetadataResolveService.php
> Metadata解決処理をトランザクション内で実行する

- webpack.mix.js
もしかして皆さんの環境ではsourcemap出てたりします？
> SourceMapが欲しい

- .eslintrc.js
- package.json
- resources/assets/js/app.ts
- resources/assets/js/bootstrap.ts
- resources/assets/js/checkin.ts
- resources/assets/js/fetch.ts
- resources/assets/js/tissue.ts
- yarn.lock
refs #458 
jQuery.ajaxの代わりにfetchを使う。TissueはIEをサポートしてないので、よほど古いスマホでもなければ大丈夫かと思います。
https://caniuse.com/#feat=fetch
> Fetch APIを使う

- resources/assets/js/@types/jquery-tissue.d.ts
- resources/assets/js/app.ts
- resources/assets/js/bootstrap.ts
- resources/assets/js/tissue.ts
- resources/views/ejaculation/show.blade.php
- resources/views/user/profile.blade.php
refs #458 
tissue.tsの中身をjQuery Pluginから単なる関数群に置き換えた。どれも共通して操作対象のElementを1つ渡して何かさせるというインターフェースで統一している。
> Replace jquery tissue plugin

- app/MetadataResolver/OGPResolver.php
> OGPResolver: リダイレクト時にCookieを維持させる

- resources/views/components/profile-bio.blade.php
- resources/views/components/profile.blade.php
- resources/views/user/base.blade.php
- resources/views/user/profile.blade.php
components.profile が /checkin/{id} でも使われているのを見落としていた。
> チェックイン個別ページのユーザープロフィールが半分消えているのを修正

- composer.lock
- resources/views/components/profile-bio.blade.php
- resources/views/components/profile.blade.php
- resources/views/user/base.blade.php
- resources/views/user/profile.blade.php
> Release 20201025.1731

- resources/views/user/profile.blade.php
> プロフィールページの概況が消えていたのを修正

- app/Http/Controllers/EjaculationController.php
- resources/assets/js/components/CheckinForm.tsx
新規チェックインの時だけ、日時入力の上にチェックボックスを追加して省略するかどうかを選べるようにする。  
日時指定を省略した場合、サーバ上の日時から秒を切り捨てたものが使用される。
> 日時指定を省略してチェックインする機能

- app/Http/Controllers/UserController.php
fix #239 
チェックインスパンの計算ではWindow関数を使用して直後の行との差分を取っていたが、この方式ではWHERE句の影響を受けるため、結果セットにプライベートチェックインが含まれている場合やオカズ抽出をしている場合に不正確なスパンが計算されていた。  
このPRでは、相関サブクエリで1つ前のチェックイン日時を求めるように変更し、そこからチェックインスパンを計算するようにする。  
ejaculations.user_idとejaculations.ejaculated_dateの組には既にインデックスが張られているため、Index Only Scanが使われることが期待できる。そのため、この手法でもパフォーマンスへの影響はあまり無いと見込んでいる。
この変更によって、スパンの値から暗にプライベートチェックインの日時が推測できてしまうことについては、現時点でも各種統計情報にはプライベートチェックインを含めた情報がパブリックに出ているので、具体的な内容が露出しなければ良いとしたいところ。
> チェックインスパンの計算手段をWindow関数から相関サブクエリに変更

- tests/Unit/MetadataResolver/CreateMockedResolver.php
> Resolverテストで複数のリクエストをモックできるようにする

- app/Http/Controllers/SettingController.php
- app/Mail/PasswordChanged.php
- resources/views/emails/password_changed.blade.php
- resources/views/setting/base.blade.php
- resources/views/setting/password.blade.php
- routes/web.php
ついにパスワード変更ができるようになります。実装こんな感じで大丈夫でしたっけ……
ついでにメール通知するようにしてみた
> パスワードの変更フォーム

- resources/views/guest.blade.php
前々から思っていたけど、夢を語るのはいいけど実現してなさすぎだと思う
> できていないことを書くのをやめる

- app/Http/Controllers/SearchController.php
fix #703 
検索クエリ全体にタグ検索用の正規化処理が通されていたため、正規化されておらず大小文字などの厳密な一致を行う検索条件において検索不能なケースが生じていた。
> タグ検索以外のキーワードは正規化しないようにする

- app/Http/Resources/EjaculationResource.php
- openapi.yaml
入れていたと思い込んでいたのだけど、そんなことはなかった。非対称であることに気づいて気持ち悪いのでレスポンスに追加する。  
ついでにドキュメントも修正。
> Webhook: レスポンスにdiscard_elapsed_timeを含める

- app/MetadataResolver/MGStageResolver.php
- app/MetadataResolver/MetadataResolver.php
- tests/Unit/MetadataResolver/MGStageResolverTest.php
- tests/fixture/MGStage/test.html
MGS動画(<https://www.mgstage.com/>)内のコンテンツ向けResolverです。
以下の情報の取得に対応しています。
- タイトル
- 作品画像
- 作品説明
- タグ
> add MGStageResolver

- app/Services/CheckinCsvExporter.php
> 33個目以降のタグがエクスポートできない不具合の修正

- .circleci/config.yml
- Dockerfile
- README.md
> DockerfileおよびCI環境をPHP 7.4にアップデート

- app/MetadataResolver/DLsiteResolver.php
ref: https://www.dlsite.com/pro/announce/=/product_id/VJ014759.html
archive: https://archive.md/R9yBb
- 恒久的にこの状態になってるページが見つからないのでテストが書けない
- 現行のテストは通ってるので他のページに副作用はないはず
> DLsiteResolver: フォローボタンがない場合にエラーになる問題を修正

- package.json
- yarn.lock
dependabotが作ってくれているが、それはそれとして設定修正込みでのPR。
IntelliJがこの体たらくなので直るまでマージしない。
> stylelint 14.6.1

- .circleci/config.yml
https://circleci.com/docs/ja/2.0/next-gen-migration-guide/
> CI: cimgに移行

- .circleci/config.yml
- Dockerfile
- README.md
- composer.json
- composer.lock
> DockerfileおよびCI環境をPHP 8.0にアップデート

- app/MetadataResolver/TwitterApiResolver.php
hotfix for #894 
- いいえ
- いいえ
- その他、デプロイにあたって特別な作業は必要ですか？(例: ワンタイムスクリプトの実行)
- なし
> Release 20220703.2132

- composer.lock
```
% composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 10 updates, 0 removals
- Upgrading composer/composer (2.2.13 => 2.2.16)
- Upgrading doctrine/annotations (1.13.2 => 1.13.3)
- Upgrading firebase/php-jwt (v5.5.0 => v5.5.1)
- Upgrading laminas/laminas-diactoros (2.8.0 => 2.13.0)
- Upgrading league/oauth2-server (8.3.3 => 8.3.5)
- Locking league/uri (6.7.1)
- Locking league/uri-interfaces (2.3.0)
- Upgrading nikic/php-parser (v4.13.2 => v4.14.0)
- Upgrading php-http/discovery (1.14.2 => 1.14.3)
- Upgrading phpseclib/phpseclib (2.0.34 => 2.0.37)
- Upgrading psy/psysh (v0.11.2 => v0.11.7)
- Upgrading symfony/dom-crawler (v4.4.30 => v4.4.42)
Writing lock file
```
> run composer update

- composer.json
- composer.lock
#900 の作業中に上げる必要に気づいたけど、先にやっておかないとPHPUnit自身の変更による影響なのか判断付かない気がする
> PHPUnit 9.5.21

- composer.json
- composer.lock
> Guzzle 7.4.5

- app/MetadataResolver/DLsiteResolver.php
- tests/Unit/MetadataResolver/DLsiteResolverTest.php
- tests/fixture/DLsite/testComic.html
OGPタイトルに "DLsite comipo" で終わるパターンが増えたので、パターンを修正。
また、テストで使っている作品のtitleに入っているのが著者じゃなくて出版社名になって、その関係でdescriptionが変わったっぽい。許容するか何とも微妙な感じ。
> DLsiteResolver: update fixture, fix test

- tests/Unit/MetadataResolver/ToranoanaResolverTest.php
- tests/fixture/Toranoana/testJoshi.html
- tests/fixture/Toranoana/testJoshiD.html
- tests/fixture/Toranoana/testJoshiR.html
- tests/fixture/Toranoana/testJoshiRD.html
- tests/fixture/Toranoana/testTora.html
- tests/fixture/Toranoana/testToraD.html
- tests/fixture/Toranoana/testToraR.html
- tests/fixture/Toranoana/testToraRD.html
一般向けのドメインが変わったらしい (.shop ってなんだったんだろうなぁ)
> ToranoanaResolver: update fixture, fix test

- app/MetadataResolver/MelonbooksResolver.php
- composer.lock
- package.json
- yarn.lock
- MelonbooksResolverの本番不具合修正
- 依存関係の更新
- いいえ
- いいえ
- その他、デプロイにあたって特別な作業は必要ですか？(例: ワンタイムスクリプトの実行)
- なし
> Release 20230814.2030

- package.json
- resources/assets/js/user/collections.tsx
- yarn.lock
- コレクション一覧に並べ替えボタンを追加 (とりあえず逆順にできるだけ)
- 依存関係の更新
- いいえ
- いいえ
- その他、デプロイにあたって特別な作業は必要ですか？(例: ワンタイムスクリプトの実行)
- なし
> Release 20231104.1730

- .github/workflows/build-image.yml
- docker/production/bin/tissue-php-entrypoint
- docker/production/php.dockerfile
> Release 2023.12.1

- app/CheckinWebhook.php
- app/ContentProvider.php
- app/Ejaculation.php
- app/Like.php
- app/User.php
- composer.json
- composer.lock
- database/factories/CheckinWebhookFactory.php
- database/factories/ContentProviderFactory.php
- database/factories/EjaculationFactory.php
- database/factories/LikeFactory.php
- database/factories/UserFactory.php
- tests/Feature/Api/V1/CheckinTest.php
- tests/Feature/Api/V1/CollectionItemTest.php
- tests/Feature/Api/V1/CollectionTest.php
- tests/Feature/Api/V1/MeTest.php
- tests/Feature/Api/V1/UserCheckinTest.php
- tests/Feature/Api/V1/UserCollectionTest.php
- tests/Feature/Api/V1/UserTest.php
- tests/Feature/Api/Webhook/CheckinWebhookTest.php
- tests/Feature/Setting/WebhookTest.php
- tests/Feature/SettingTest.php
- tests/Unit/Services/CheckinCsvImporterTest.php
- tests/Unit/Services/MetadataResolverServiceTest.php
`laravel/legacy-factories` をいつまでも入れとくのも嫌だなと思って滅ぼしました
> クラスベースのfactoryに移行

- package.json
- resources/assets/js/api.ts
- resources/assets/js/collect.tsx
- resources/assets/js/query.tsx
- resources/assets/js/user/collection.tsx
- resources/assets/js/user/collections.tsx
- yarn.lock
> react-query v4

- resources/views/layouts/base.blade.php
設定画面まで行かないと開けないのは、ちょっと遠いなと思ったので。
> フッターにAPIドキュメントへのリンクを追加

- .github/workflows/build-image.yml
#1152 対策で、write権限持ちのorg memberがPR指定して実行できればいいのでは? という発想
> build-image workflowをworkflow_dispatchで実行できるようにする

- app/MetadataResolver/PixivResolver.php
> PixivResolver AI生成タグを追加

- package.json
- redocly.yaml
- yarn.lock
知らない間にredoc-cliがdeprecatedになっていたので置き換え。
> Upgrade redoc-cli to @redocly/cli

- .circleci/config.yml
- README.md
- composer.json
- composer.lock
- docker/development/web.dockerfile
- docker/production/foundation.dockerfile
- docker/production/php.dockerfile
> DockerfileおよびCI環境をPHP 8.1にアップデート

- docker/development/web.dockerfile
- docker/production/foundation.dockerfile
> Docker: node 22.6.1にアップデート

- app/MetadataResolver/MelonbooksResolver.php
- tests/fixture/Melonbooks/testCensored.html
- tests/fixture/Melonbooks/testUncensored.html
> MelonbooksResolver: ページタイトル内の丸括弧が半角化されたことに伴う抽出正規表現の修正

- app/MetadataResolver/FantiaResolver.php
- app/Providers/AppServiceProvider.php
- #1307
- いいえ
- `fantia.jp/posts/` を含むURL
- なし
> Release 2024.10.0

- composer.lock
- 脆弱性対応 (#1326)
- いいえ
- いいえ
- なし
> Release 2024.11.0

- app/Http/Controllers/Admin/ReportController.php
- app/Http/Controllers/Admin/RuleController.php
- app/Http/Controllers/EjaculationController.php
- app/Http/Controllers/EjaculationReportController.php
- app/Http/Requests/AdminRuleStoreRequest.php
- app/Http/Requests/EjaculationReportRequest.php
- app/Mail/EjaculationReported.php
- app/Mail/Moderated.php
- app/Moderation.php
- app/ModerationAction.php
- app/Report.php
- app/Rule.php
- app/User.php
- database/migrations/2024_10_05_153922_create_rules_table.php
- database/migrations/2024_10_05_153923_create_reports_table.php
- database/migrations/2024_11_23_002538_create_moderations_table.php
- resources/assets/js/admin/rules.ts
- resources/views/admin/reports/index.blade.php
- resources/views/admin/reports/show.blade.php
- resources/views/admin/rule/create.blade.php
- resources/views/admin/rule/edit.blade.php
- resources/views/admin/rule/index.blade.php
- resources/views/components/ejaculation.blade.php
- resources/views/ejaculation/report.blade.php
- resources/views/emails/.editorconfig
- resources/views/emails/ejaculation_reported.blade.php
- resources/views/emails/moderated.blade.php
- resources/views/layouts/admin.blade.php
- routes/web.php
shikorism.net で、Googleフォームと手動のメール送信でやっていた事務作業の機能化。
> チェックインの通報機能

- README.md
- composer.lock
- #1368 
- #1369
- いいえ
- いいえ
- なし
> Release 2024.12.2

- composer.lock
> Release 2024.12.3

- app/Http/Controllers/SearchController.php
> ログインユーザーの非公開チェックイン・コレクションを検索結果に含める

- app/Http/Controllers/SearchController.php
- app/Http/Controllers/UserController.php
- app/Http/Requests/EjaculationReportRequest.php
- composer.json
- composer.lock
- resources/assets/js/user/stats.ts
- resources/views/user/stats/yearly.blade.php
- yarn.lock
- #1375 
- #1380
- いいえ
- いいえ
- なし
> Release 2024.12.4

- package.json
- resources/assets/js/components/Pagination.tsx
- resources/assets/js/user/collection.tsx
- resources/assets/js/user/collections.tsx
- yarn.lock
https://reactrouter.com/7.4.0/upgrading/v6 の手順通りに実施しただけ。
> React Router v7

- app/MetadataResolver/MelonbooksResolver.php
- tests/fixture/Melonbooks/testCensored.html
- tests/fixture/Melonbooks/testUncensored.html
ページタイトル内の丸括弧が半角から全角に変わっていたので正規表現を修正しました。
これに伴い、テストに使用しているファイルを更新しました。
> MelonbooksResolver: タイトルの解決を修正

- .devcontainer/compose.yaml
- .devcontainer/devcontainer.json
- .devcontainer/postCreateCommand.mjs
- .gitignore
- .vscode/launch.json
Devcontainer無いのって言われたので作ってみたけど、VSCode使いじゃないのでこれでいいのか分からない。
env_fileを読み込まないようにしたのは、セットアップ手順実行前に開いた時の詰み防止。たぶんここで読まなくてもLaravelは.envを読んだはず……
> add .devcontainer/devcontainer.json

- resources/views/home.blade.php
fix #1252
Eloquent CollectionならisNotEmpty使えるじゃんね
> お知らせ欄の表示判定ミスを修正

- app/User.php
- openapi.yaml
- tests/Feature/Api/V1/MeTest.php
ProfileStatsComposerから中央値の集計処理をコピペして実装。
> API: User.checkin_summaryに中央値を追加

- app/Http/Controllers/Api/V1/UserLikeController.php
- openapi.yaml
- routes/api.php
- tests/Feature/Api/V1/UserLikeTest.php
使っているクエリは UserController::likes からコピペしたもの。
> API: GET /api/v1/users/:username/likes (いいね一覧) の追加
