app/Http/Controllers/EjaculationController.php
resources/views/ejaculation/checkin.blade.php

要望を感じたので、チェックイン画面でクエリパラメータから初期値を受け付けるようにした。  
まだ問題点があるので修正が必要。
* クエリパラメータから初期値を投入  
→初期値の入った項目を空にする  
→チェックイン  
→入力チェックエラー  
の流れになった場合、入力を消した欄にクエリパラメータの初期値が復活してしまう。  
手で消した以上、その場合は空であるべき。

チェックイン画面でクエリパラメータを受け付ける

---

app/MetadataResolver/DLsiteResolver.php
app/MetadataResolver/MetadataResolver.php

DLsiteのOGPURL
```
https://img.dlsite.jp/modpub/images2/work/doujin/RJ******/RJ******_img_sam.jpg
```
から、
メイン画像
```
https://img.dlsite.jp/modpub/images2/work/doujin/RJ******/RJ******_img_main.jpg
```
に変換するリゾルバです。
`MetadataResolver.php`の正規表現(\d+あたり)に不安があるので見てもらえると助かります。

DLsiteResolverを追加

---

Dockerfile

```
Package operations: 84 installs, 0 updates, 0 removals
Failed to download symfony/thanks from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini                                                          
Now trying to download from source
- Installing symfony/thanks (v1.1.0): Cloning 9474a631b5 from cache
Failed to download vlucas/phpdotenv from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini                                                          
Now trying to download from source
```
のような警告を出さないようにする

composer installでdistから取れるようにする

---

resources/views/auth/login.blade.php
resources/views/auth/passwords/email.blade.php
resources/views/auth/passwords/reset.blade.php
resources/views/auth/register.blade.php

`type="email"` にするとブラウザ側でメールアドレスのバリデーションを行えます。
また環境によってはスクリーンキーボードに `@` や `.` が追加され、UXの向上に繋がります。

メール欄のtypeをemailに変更

---

resources/views/home.blade.php
resources/views/search/index.blade.php

現状ではdisplay_nameは設定できないため同じだが、こちらのほうが好ましいはず。

パブリックタイムラインと検索画面で出るチェックインユーザーの名前をdisplay_nameにする

---

README.md

`artisan key:generate` で作成したキーを読むために必要です。

構築手順の最後に.envの読み直しを追記

---

app/MetadataResolver/KomifloResolver.php

未ログインで取得できる情報なので問題ないと考えていますが、問題があるようであればcloseしてください。
Komiflo APIで取得できるサムネイル画像のサイズは
```
0: "148_desktop_small"
1: "296_desktop_small_2x"
2: "198_desktop_medium"
3: "396_desktop_medium_2x"
4: "247_desktop_large"
5: "494_desktop_large_2x"
6: "160_mobile_narrow"
7: "320_mobile_narrow_2x"
8: "207_mobile_medium"
9: "414_mobile_medium_2x"
10: "188_mobile_large"
11: "376_mobile_large_2x"
12: "564_mobile_large_3x"
13: "346_mobile"
```
があるようです。
現在Tissueでは `.col-md-6` でオカズリンクの `.card` を表示していて、そのコンテナが `.col-lg-8` のため、画像は最大で342pxで表示されるようです。
高DPIな環境を想定して342pxの2倍、684px程度あると良さそうだったので取得できる最も大きなサムネイルの `564_mobile_large_3x` を使用しています。

KomifloResolverに画像の取得を追加

---

public/css/tissue.css
resources/views/layouts/base.blade.php

fix #19
* 非ログイン時は body に `tis-need-agecheck` class を追加
* クッキーに `agecheck` がなければモーダル表示してからクッキー設定、なければ上記 class を消す
という単純な実装です。文言は適当なので他のがよければ指摘してください。
だめなところ
* CSS の filter なので、古いブラウザやテキストブラウザには効かないし、ダウンロードはされる
* JavaScript が無効になってるとモーダルだけ表示されなくて驚きの白さ™
* 普通に今script書いてるとこでfilterかけたら画像はともかくテキストはチラ見えしてしまったので、安全側に倒してみた。なんとかしようはあるかも。

非ログイン時は年齢確認を表示するように

---

app/MetadataResolver/PixivResolver.php

fix #76
mode=mangaもログイン必須だったのでmediumではなくmanga_bigに寄せて、どちらの場合でもページ数がなければ最初のページを取得する形にしました。

Pixivのmode=mangaに対応

---

public/css/tissue.css

わけわからんことになりそうなのでブラーのかかっているところはリンクをクリックできないようにする。

年齢確認の画面で隠されているところのリンクをクリックできないように修正

---

resources/views/auth/register.blade.php

ref #46 
登録メールアドレスに紐付いたGravatarを利用することを明示します。登録をもって同意とすることまで書くべきでしょうか……。
「使用しているメールシステムによってはエイリアス機能が提供されていることがあるので、そちらで回避することもできます」みたいな、回避策には触れませんでした。

新規登録時に、Gravatarの利用についての案内を表示

---

app/Http/Controllers/SettingController.php
app/Http/ViewComposers/ProfileStatsComposer.php
app/Providers/ViewComposerServiceProvider.php
database/migrations/2019_02_06_235832_add_bio_and_url_to_users.php
resources/views/components/profile-stats.blade.php
resources/views/components/profile.blade.php
resources/views/home.blade.php
resources/views/setting/profile.blade.php

ユーザーページの情報欄に、自己紹介とURLを書けるようにしました。~~後者はTissueのURLをMastodonに貼って認証済みにしたかっただけです。~~
また、この機能追加の影響で情報欄の内容量が増えてきたため、ユーザーページとホームのユーザ情報レイアウトを別のものにしました。  
セッション・概況部分を `components.profile` から分割して、各レイアウトから参照する風にしています。
`components.profile` の名前回りの段組みをリバートしていますが、ホームで表示されるほうには引き続き採用しています。
ユーザーページとレイアウトを分けたついでに、前よりコンパクトにしました。

プロフィール設定機能の強化 (自己紹介文, URL)

---

dist/php.d/99-xdebug.ini

`xdebug.remote_autostart` を有効にすると、ブラウザでの特別な操作の必要なくデバッガーを立ち上げられて便利。
しかし、デバッガーを使う必要のない時まで接続待ちをしてしまって、アプリケーションコードが走るまでの時間が長びいてしまう。これはやる気を削ぐ理由になるので、設定を削除する。
この設定を使わずにデバッガーを起動したい場合、 `XDEBUG_SESSION` というキーでCookieをセットすれば起動できる。これは[拡張機能](https://www.jetbrains.com/help/phpstorm/browser-debugging-extensions.html)や[ブックマークレット](https://www.jetbrains.com/phpstorm/marklets/)で簡単にセットできるので、こちらを利用すると楽。

重すぎるので xdebug.remote_autostart の利用を廃止

---

app/MetadataResolver/ActivityPubResolver.php
app/MetadataResolver/MetadataResolver.php
app/MetadataResolver/OGPResolver.php
app/MetadataResolver/Parser.php

要するにMastodon対応です。Mastodonのog風のメタデータをActivityPubのNoteとActorから自力で構築しています。
MetadataResolverはこれまでURLとの正規表現マッチでResolverを選択するのみでしたが、今回ActivityPub対応のため「対応形式をAcceptに突っこんでGETした時のContent-Type」を見て分岐するロジックを新たに追加しました。元々は単にActivityPubResolverからOGPResolverにフォールバックしようかと考えていたんですが、その依存もなんだかなあと思ったのでこうなりました。
今後の展開としては画像直リンとかにも使えるんじゃないですかね（？）
optional:
* 画像以外の添付（動画とか）は蹴る
* メディアがなければ著者近影にフォールバックする
* CWもdescriptionに取り込む
* テストを書く

ActivityPubResolverを追加

---

app/Http/Controllers/HomeController.php
public/css/tissue.css
public/js/tissue.js
resources/views/ejaculation/show.blade.php
resources/views/home.blade.php
resources/views/layouts/base.blade.php
resources/views/search/index.blade.php
resources/views/user/profile.blade.php

* (PCのみ) お知らせ欄を小さい方のカラムに移動。お惣菜の領域を稼いだ。
* サーバ内全体の日々のチェックイン数を集計して表示。致し日和なのかが可視化される。
* お惣菜コーナーから大枠を削除。ユーザープロフィール画面と見た目を合わせた。
* ついでにカード表示処理を共通化して、インラインJSを減らした。

ホーム画面の微リニューアル

---

app/MetadataResolver/PixivResolver.php

PixivのOGPに指定されている `embed.pixiv.net` はIDやタイトルも表示されていて有用でしたが、それらは表示されなくなったうえ、画像の一部しか見えないようになってしまいました。
このPRでは `embed.pixiv.net` を使用しないで、すべての作品（全年齢/R-18/漫画）でプロキシURLを使用するようにします。
ついでに正規表現の置き換えの重複箇所がなくなりシンプルになります。

pixivのOGP画像で常にプロキシURLを使用する

---

docker-compose.mailcatcher.yml

[mailcatcher](https://mailcatcher.me/)で開発時の送信メールをDocker完結で扱えるようにする
```example up
docker-compose -f docker-compose.yml -f docker-compose.mailcatcher.yml up -d
```
```.env
MAIL_DRIVER=smtp
MAIL_HOST=mailcatcher
MAIL_PORT=1025
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=
MAIL_FROM_ADDRESS=support@mail.shikorism.net
MAIL_FROM_NAME=Tissue
```

Dockerでmailcatcherを使えるようにする

---

public/css/tissue.css
resources/views/layouts/base.blade.php

Ref: #107
非ログイン
ログイン時
---
少し寂しいのでアイコンを追加してみた版もあります。
こちらを使う場合はもう少し余白を広げたほうが良さそう。

モバイルのナビメニューを整える

---

public/css/tissue.css
public/js/tissue.js
resources/views/components/link-card.blade.php

カードのレイアウトを横向きにします。
現状の縦向きだと右に空きスペースがあるので横のほうがいい感じなきがしています。
モバイルだと縦向きになります。

カードのレイアウトを横向きに

---

public/manifest.json
public/sw.js
resources/views/layouts/base.blade.php

fixes #96 
Web Share Target API （っていうかPWA）は https で配信しないと動かないので、試す時はngrokとか使うとよいです。Laravelがプロトコル誤判定するようなら [TrustProxies](https://laravel.com/docs/5.5/requests#configuring-trusted-proxies) 入れましょう。わたしは入れました。
* Android版Chromeの場合:
* 画面下に出てくる「ホーム画面に Tissue を追加」、もしくは右上のメニューから追加。
* 任意のアプリからURLを共有 → Tissue を選択 → チェックイン画面
* PC版Chrome（少なくともWindows版）の場合:
* Experimental Web Platform features を有効にする必要がある
`chrome://flags/#enable-experimental-web-platform-features`
* Tissueを開いて、右上のメニューから `「Tissue」をインストールしています‥」` を選択
* Web Share API を使ったサイト*1から共有 → Tissue を選択 → チェックイン画面
*1: Mastodon、Qiita、etc.
* その他ブラウザ・iOSの場合:
* https://www.chromestatus.com/feature/5662315307335680
<details><summary>demo gif</summary>
</details>
* Web Share Target を実装
* 共有されると `/checkin?link={url}` を開きます。
* title, text, url …

Web Share Target 実装（のためにPWA対応）

---

tests/Unit/MetadataResolver/DLsiteResolverTest.php
tests/fixture/DLsite/testProduct.html
tests/fixture/DLsite/testProductSP.html

DLsiteResolverのテストを追加します。
DLsiteには`home`(全年齢向け 同人作品)、`maniax`(R18 男性向け 同人作品)、`eng`(全年齢向け 英語)などの販売項目がありますが、OGPの出力に差はないようでしたので、R18作品のPCサイトとSPサイトのテストのみを追加しました。
ref #42

DLsiteResolverのテストを追加

---

app/MetadataResolver/PatreonResolver.php

token-timeがない場合（有料限定のため汎用画像が使われる場合）にエラーが出るので。

PatreonResolverにてtoken-timeがある場合のみexpires_atを指定するように変更

---

app/MetadataResolver/MetadataResolver.php
tests/Unit/MetadataResolver/DLsiteResolverTest.php

DLsiteではツイートボタンを押したときに `https://dlsite.jp/mawtw/作品ID` のURLが使われます。
これは現在の正規表現パターンに一致しないためパターンを追加しました。

DLsiteResolverをdlsite.jpの形式に対応させる

---

package.json
resources/views/home.blade.php
resources/views/layouts/base.blade.php
resources/views/user/stats.blade.php
webpack.mix.js
yarn.lock

jQueryやchart.jsなど、複数のエントリポイントから呼び出されているモジュールが重複してロードされるため無駄が多くなっていた。これらを外出しすることによって容量の最適化を行うと同時にベンダモジュールをブラウザにキャッシュさせやすくできる。
あわせて`mix.version()`でアセットURLにハッシュを含めるようにした。
また、bundle-analyzerもついでに。

複数のエントリポイントから共通して利用されているベンダモジュールを外出し

---

resources/assets/sass/app.scss
resources/assets/sass/components/_link-card.scss
resources/assets/sass/tissue.css

https://github.com/shikorism/tissue/issues/87#issuecomment-470697153 にて提案された `white-space: pre-line` を用いて、metadata.description の改行が表示上に反映されるようにしました。
テキストが長すぎる場合は、適当な所で省略します。
> ![image](https://user-images.githubusercontent.com/1352154/54042608-df4ec400-420d-11e9-8bb5-a0b94872d538.png)
> リンク先: https://ertona.net/@shibafu528/101716004483801313
close #87

メタデータのdescriptionに含まれる改行を表示に反映する

---

app/MetadataResolver/MetadataResolver.php
app/MetadataResolver/PlurkResolver.php
tests/Unit/MetadataResolver/PlurkResolverTest.php
tests/fixture/Plurk/test.html

台湾のユーザーはつかうかもしれない。
Plurkはアダルト判定されている画像はOGPに出ないのでその対応です。
最初の画像があればそれを、なければOGPにフォールバックします。
アダルト判定されている画像を見るにはログインが必要ですが、アカウントがなくても https://www.plurk.com/search?q=R-18 らへんからパーマリンクは取得できます。

PlurkResolverを追加

---

resources/assets/js/app.js
resources/views/ejaculation/show.blade.php
resources/views/user/profile.blade.php

Bootstrapに任せると問答無用でModalを召喚しようとするので、自力で呼び出すようにしてみた。こっちにはこっちの都合というものがある。
まぁこれだと、DOMContentLoadedまでの間に触るとページの天井に頭をぶつけるけど、壊れたダイアログが出るよりは……。
fix #145

削除モーダルの初期化が完了してから削除ボタンクリックイベントを仕掛ける

---

resources/assets/sass/_bootstrap-custom.scss
resources/views/components/link-card.blade.php

https://github.com/shikorism/tissue/issues/140#issuecomment-471278788 で書いた案をそのままPRにしました。
レイアウトに応じてCSSを付け変えるのも面倒なので、メディアクエリに任せてしまえばいいという魂胆です。
fix #140

カード画像の角丸の位置をメディアクエリで可変にした

---

app/Http/Controllers/EjaculationController.php
app/Http/Kernel.php
app/Http/Middleware/NormalizeLineEnding.php
tests/Unit/Http/Middleware/NormalizeLineEndingTest.php

#1 の対応を行った際に改行コードを正規化する処理を実装したが、これは個別に処理するものではなくて全体で統一されるべき振る舞いなのでは？と思い直した。
ということで、その処理をミドルウェア化してWebグループに設定した。
APIグループには設定していないが、そっちでも統一しておいたほうが良いだろうか……。  
(そうであれば、いっそグローバルに仕掛けるのが良いのかな)

改行コードを正規化する処理をミドルウェア化

---

app/MetadataResolver/DLsiteResolver.php
tests/Unit/MetadataResolver/DLsiteResolverTest.php

冗長な定型文を削除します。
改行文字を使用しているため、使用する場合は #87 の対処が必要です。

DLsiteResolverで余分な説明文を削除・整形する

---

dist/bin/tissue-entrypoint.sh
dist/php.d/99-xdebug.ini

コンテナ用のxdebug設定ではコールバック先を `host.docker.internal` に決め打ちしていましたが、これはDocker for Windows/Macで暗黙に定義されるホスト名であるため、Linux環境では使えません。
そのため、試しに `host.docker.internal` が名前解決できるかテストしてみて、解決できればそのまま使用し、だめなら自身のIPv4アドレスの第4オクテットを 1 にしたものがホストのアドレスであると仮定するように変更しました。
……ソースはQiitaなんですけど、これ本当に良いんですかね？

Linux+Dockerな開発環境でxdebugが使えるようにコールバック先IPアドレスの設定を調整

---

resources/assets/sass/app.scss
resources/views/layouts/base.blade.php

このPRはBootstrapのプライマリカラーを `#e53fb1` に変更します。
faviconはピンクなのに、リンクなどのプライマリカラーがBootstrapデフォルトの青であることが気になったためです。それとブランディングのためにテーマカラーがあると便利なので。
faviconなどで使われている背景色は `#e040fb` ですがそのままプライマリカラーにするには眩しすぎたので、Bootstrapのpink `#e83e8c` とブレンドしたものです。
色は個人の感性によるものが強いですので、気に入らなければcloseしてもらってまったく問題ありません。

プライマリカラーを変更

---

public/manifest.json

ホーム画面に追加したアイコンから起動すると、ブラウザ枠に色がつきます。
Chrome for Windows
Chrome for Android

manifest.jsonにテーマカラーを追加

---

resources/views/home.blade.php
resources/views/search/index.blade.php
resources/views/timeline/public.blade.php

名前欄の書字方向を独立させるためのマークアップとして `<bdi>` タグを使用してみた。 (https://github.com/shikorism/tissue/issues/128#issuecomment-474901827)
refs #128

チェックインビュー上のdisplay_nameをbdiタグでマークアップ

---

app/Http/Controllers/UserController.php

グラフの表示範囲は当月までしか想定していなかったが、取得範囲を制限していないために未来のチェックインで障害を起こしていた。
当日まで・当月末までどちらにするかちょっと悩んだが、表示しているグラフがだいたい月単位で描画されているので当月末までとした。
fix #165

グラフ画面で表示するデータ範囲を当月末までに制限

---

app/MetadataResolver/ActivityPubResolver.php

`DOMDocument::loadHTML()` に空のHTMLを渡すとエラーになってしまうため、その場合は何もしないようにします。
fix #174

ActivityPubResolverでcontentが空のときはHTMLとしてのパースを行わないようにする

---

resources/assets/js/checkin.js

特定の環境(※今回事象が確認されたのはmacOS)において、全角文字を含むタグの入力が正常に行えない問題に対応する修正です。
Keyboard​Event​.isComposingが生えてない環境では従来通りの挙動となります。

特定条件下においてタグ入力が正常に行えない問題の修正

---

app/Http/Controllers/Api/CardController.php
app/Listeners/LinkCollector.php
app/Metadata.php
app/MetadataResolver/KomifloResolver.php
app/MetadataResolver/Metadata.php
app/MetadataResolver/PixivResolver.php
database/migrations/2019_04_29_111019_create_metadata_tag_table.php

#105 を何かしらの形で実現するための下準備です。
metadata テーブルと tags テーブルにリレーションを設定し、タグ情報の保存をサポートします。
また、Resolver側実装サンプルとして、KomifloResolverとPixivResolverで実際にタグを保存するようにしました。
ref #40

MetadataResolverからタグ情報を保存できるようにする

---

yarn.lock

セキュリティfixも入ってるらしいですね。まだしばらくjQueryには働いてもらうぞ。
* https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/
* https://blog.jquery.com/2019/05/01/jquery-3-4-1-triggering-focus-events-in-ie-and-finding-root-elements-in-ios-10/

jQuery 3.4.1にアップデート

---

app/MetadataResolver/PixivResolver.php

`array_search()`  の戻り値は、見つからなければ `FALSE`、見つかれば 0 以上のインデックス。
たぶんこの修正前の式だと「R-18」(index 0)を素通ししてしまう。

PixivResolverのタグ抽出がおそらく「R-18」を無視できていないのを修正

---

.env.example

READMEのテストの項目にも追記するべきかもしれない（乱用されると困るかも）

.env.exampleにTEST_USE_HTTP_MOCKを追加

---

resources/assets/sass/components/_link-card.scss
resources/views/components/link-card.blade.php

大きな画像を表示した際に無制限に高さを取らないように、また今後プレースホルダを置きたくなった時の目安になるよう高さを固定します。
fix #137

サムネイルを含むカードを高さ400pxに固定し、トリミング表示されるように変更

---

resources/assets/sass/components/_link-card.scss

たぶん参考資料の通りの現象だと思うので、雰囲気で修正した。
iOSデバイスを持ってないので確かめられない(絶望) おのれAppleめ……
* https://glatchdesign.com/blog/web/css/1254
* https://qiita.com/takanorip/items/4e8d4c92bcbc34a954bb
fix #200

iOS対策 カード省略グラデーションの透明色指定をtransparentからrgba()に変更

---

app/MetadataResolver/MetadataResolver.php

howtw, cowtw, sowtw, maatw, bowtw, prwtw 等があるため

DLsiteResolverのtwitterリンクの正規表現を修正

---

app/MetadataResolver/MetadataResolver.php
app/MetadataResolver/SteamResolver.php
tests/Unit/MetadataResolver/SteamResolverTest.php
tests/fixture/Steam/test.json
tests/fixture/Steam/testNotFound.json
tests/fixture/Steam/testR18.json

最近流行りの成人向けSteamゲームを表示できるようにする対応です。
具体的には https://store.steampowered.com/app/1077580 など。
テストも書きたいんですがAPIを必要とするテストの書き方がわからないです……

SteamResolverを追加

---

app/Http/ViewComposers/ProfileStatsComposer.php
resources/views/components/profile-stats.blade.php

利用していなかった期間の長いユーザーの場合に実態とかけ離れてしまうのを軽減したいのと、現状に近い値が取れたほうが分かりやすいのではないかという意図があります。
でもこのSQLの投げかたは、なんかなあ……

平均記録を直近30チェックインから算出するように変更

---

app/Utilities/Formatter.php

fix #218 
`Formatter#linkify` でリンク化する際にオプションを設定して `target="_blank" rel="noopener"` が付くようにしました。
対象となるユーティリティメソッドは「チェックインのノート」「プロフィールの自己紹介」でしか使われていないので、全てに影響しても問題ないと判断しました。

ユーザー入力テキストをLinkifyする時に target="_blank" rel="noopener" を付与する

---

app/MetadataResolver/PixivResolver.php
tests/Unit/MetadataResolver/PixivResolverTest.php

`original`だと画像がでかすぎてスマホとか死んでしまう恐れがあるので`regular`に変更

PixivResolverの取得画像をregularにする

---

app/User.php

Gravatarのデフォルトのアイコンをretroにして別ユーザーで同じアイコンを使われないようにします。
現状デフォルトアイコンのユーザーが多くいいね一覧などでどれが誰だか分かりづらいのでこのPRを作りましたが、デフォルトアイコンがユニークなものだとユーザーは「アイコン変えなくてもいいか」と思ってしまう懸念もあります。

Gravatarのデフォルトアイコンをretroにする

---

app/Http/Controllers/Api/CardController.php
app/Metadata.php
app/Tag.php
resources/assets/js/checkin.ts
resources/assets/js/components/MetadataPreview.vue
resources/assets/js/components/TagInput.vue
resources/assets/sass/components/_link-card.scss
resources/views/ejaculation/checkin.blade.php
resources/views/ejaculation/edit.blade.php

オカズリンクの入力後に自動でメタデータを取得し、MetadataResolverによってタグが提供されている場合は候補として表示するようにします。
refs #105

チェックイン時にメタデータからタグをサジェストする

---

resources/assets/js/components/MetadataPreview.vue
resources/assets/js/components/TagInput.vue

TagInputの状態更新時にタグセットを配信する処理を持たせて、MetadataPreview側はそれを購読して入力済みタグ候補の色を変更できるようにした。
Video: https://social.mikutter.hachune.net/@shibafu528/102383357982969143
fix #236

入力済みのタグ候補の背景色を変更する

---

app/MetadataResolver/ToranoanaResolver.php
tests/Unit/MetadataResolver/ToranoanaResolverTest.php
tests/fixture/Toranoana/testJoshi.html
tests/fixture/Toranoana/testJoshiD.html
tests/fixture/Toranoana/testJoshiR.html
tests/fixture/Toranoana/testJoshiRD.html
tests/fixture/Toranoana/testTora.html
tests/fixture/Toranoana/testToraD.html
tests/fixture/Toranoana/testToraR.html
tests/fixture/Toranoana/testToraRD.html

OGP画像が代替イメージになっててどうしようもないので、商品画像の1枚目を取ってくるようにした。
fix #235

ToranoanaResolverで、OGP画像の代わりになりそうなサムネ画像を取得する

---

app/Http/Controllers/UserController.php
package.json
resources/assets/js/user/stats.js
resources/views/user/stats.blade.php
yarn.lock

年単位で表示期間を指定できるようにした。なお、現在年を選択した場合は範囲が1〜12月ではなく、直近12ヶ月の表示になる。

月間チェックイングラフの表示期間を選択可能にする

---

.circleci/config.yml
Dockerfile

まず開発環境をPHP 7.3にします。
本番環境の更新が完了するまでは、PHP 7.1までの機能を使用してPHP 7.3で動作確認とします。  
この期間はなるべく短く済むようにします。
refs #245

DockerfileおよびCI環境をPHP 7.3にアップデート

---

resources/assets/js/components/TagInput.vue

fix #231 
本PRにおける現状の制約事項
・Androidだとスペース文字入力後にさらに文字を入力するかスペース文字を2回入力しないとタグ入力が確定されない。(キー入力確定時のキーイベントが拾えてないっぽい？)

タグ入力確定時のフォールバック処理を追加

---

app/Http/Controllers/SettingController.php
resources/views/setting/profile.blade.php

プロフィール設定上のメールアドレス欄を入力可能にします。
バリデーションルールは RegisterController からパクってきた。
fix #262

メールアドレスを変更可能にする

---

app/MetadataResolver/NicoSeigaResolver.php
tests/Unit/MetadataResolver/NicoSeigaResolverTest.php
tests/fixture/NicoSeiga/seiga.html
tests/fixture/NicoSeiga/shunga.html

ニコニコ静画の解決の際、タグ情報を取得するようにした。春画の場合、確定で「R-15」タグが入ってくるので、これは省くようにしている。
また、サムネイルURLはhttpsに変更した。
refs #42

ニコニコ静画のタグを取得する & テストの追加

---

tests/MyAsserts.php
tests/Unit/MetadataResolver/NicoSeigaResolverTest.php

タグロックされていないタグは、実リクエストを伴うテストの度にだいたい変わっているので毎回コケてキリがない。なので、カテゴリタグとロックタグで手を打とうかなという次第です。
追加したassertは数値添字の1次元配列しか想定してないです。

NicoSeigaResolverTest: ロックされているタグのみを検証する

---

app/MetadataResolver/NijieResolver.php
tests/Unit/MetadataResolver/NijieResolverTest.php
tests/fixture/Nijie/testHasHtmlInAuthorProfileResponse.html

ニジエの作者プロフィールにはHTMLが含まれていることがあります。それが抽出対象のJSON内にエンティティ変換を施した状態で含まれていて、html_entity_decode()によって `&quot;` も巻き込んで解除してしまうことで、JSONを破壊してしまっていました。
html_entity_decode() のオプションで除外しても良いのですが、改行以外は一応JSONとして正当なはずですから、安全に倒してJSONとしてのデコードを済ませてから処理するように変更しました。

NijieResolver: JSONデコード後にHTMLエンティティのデコードを行う

---

app/MetadataResolver/DLsiteResolver.php
app/MetadataResolver/MetadataResolver.php
tests/Unit/MetadataResolver/DLsiteResolverTest.php

https://shikorism.net/checkin/5877 のように新しいアフィリエイトURLに対応していなかったので対応しました。
現状`/dlaf/=`の後に
- `/t/s`
- `/t/t`
が追加されただけのようですが、他の文字でもたぶん動きます。

DLsiteResolver 新しいアフィリエイトURL構造に対応

---

app/Http/Controllers/EjaculationController.php

新規作成・更新時に、空文字列のタグは捨てるように修正。
refs #295 
```
$ docker-compose run --rm web php artisan tinker
$ php artisan tinker
$t = Tag::where("name", "=", "")->first()
DB::table("ejaculation_tag")->where("tag_id", $t->id")->delete()
$t->delete()
```

空文字列のタグは保存せず捨てる

---

app/MetadataResolver/MetadataResolver.php
app/MetadataResolver/PixivResolver.php
tests/Unit/MetadataResolver/PixivResolverTest.php

`https://www.pixiv.net/en/artworks/~`のような形式に対応します。
今の所韓国語と中国語ではURLは変わらないようです。

PixivResolver 英語版に対応する

---

app/MetadataResolver/ActivityPubResolver.php
app/MetadataResolver/MetadataResolver.php
app/MetadataResolver/UnsupportedContentException.php

fixes https://github.com/shikorism/tissue/issues/157
ActivityPubのActorは自分で頑張らんでもOGPResolverでいい感じに見れるでしょ、ということでそのようにしました。
なおMastodonの場合、アバターのURLはアップロードする度に変化するので、アバター変更されると画像のリンクは切れます。
<details>
<summary>sample</summary>
before:
after:
</details>

MastodonのプロフィールURLをいい感じに表示する

---

phpunit.xml
tests/Feature/SettingTest.php

https://github.com/shikorism/tissue/pull/299#discussion_r357143108 への対応。
テスト時にはphpunit.xml内に記載されている環境変数が設定されていることが期待されるが、docker-composeで環境変数を設定していると上書きされてしまう。  
この挙動は思わぬ状態でテストが実行される原因になるので、phpunit.xml内でforce属性を付けて上書きされないようにする。

phpunit.xml内の環境変数を強制適用する

---

resources/assets/js/user/stats.js

statsのグラフでカーソルに近い位置のツールチップを表示する

---

dist/bin/php-debug.sh

PhpStormでデバッグ実行する時に使えるラッパーを追加します。
既存の状態ではなぜか上手く動いてくれなかったので、強制的にデバッグ有効でPHPのCLIを実行するようなものです。おま環かもしれないけど。
↓ここの "PHP executable" に指定して使っています

IDEからのデバッグ実行用ラッパーを追加

---

app/Http/Controllers/HomeController.php
resources/views/home.blade.php

表題に加えて「もっと見る」リンクの遷移先を2ページ目に変更しています。
fix #325

トップページのお惣菜表示量をお惣菜コーナー1ページ分にする

---

yarn.lock

jQuery 3.5.0 + Bootstrap 4.4.1 の組み合わせで、メニューの展開などができない問題が起きています。これはjQuery側の問題で、3.5.1で修正されたのでアップデートします。
* https://yysk.icu/@kozue/104142876511327665
* https://mstdn.maud.io/@pikepikeid/104142887397009839
* https://social.mikutter.hachune.net/@shibafu528/104142918868080022

Bump jquery from 3.5.0 to 3.5.1

---

app/Http/Controllers/UserController.php

fix #334 
もしかしたら、オカズを一覧するためのページだから余計なものを消していたのかもしれませんが、意図の記録が出てこなかったので変えます。  
タイムラインとほぼ同じ出し方をしている間は、なるべく同様の表示になるようにしておきましょう。

/user/{name}/okazu にもいいねしたユーザーのアイコンを表示する

---

app/Console/Commands/DedupTags.php
app/Http/Controllers/Api/CardController.php
app/Listeners/LinkCollector.php
app/MetadataResolver/Metadata.php
database/migrations/2020_02_22_164304_add_unique_constraint_to_tag_relations.php
tests/Unit/MetadataResolver/MetadataTest.php

1. DBに登録する前に重複を除去する
2. 既にDB上に存在する重複タグを名寄せして削除する
3. DBの多対多テーブルにunique制約をかける
#330

メタデータのタグ重複対策

---

app/MetadataResolver/MetadataResolver.php

なろう作品のURLのうち、2013年以前の作品などにおいて作品IDの末尾にアルファベットが1文字しか含まれない場合があるが、それにマッチングしていなかった。最初期については調べられていないので不明。
ex) 薬屋 https://ncode.syosetu.com/n9636x/

古いなろう作品のIDにマッチングするように

---

resources/assets/js/components/TagInput.vue

#414 の修正です。
ここでは<https://github.com/shikorism/tissue/issues/414#issuecomment-646325707>の1に倣って代替文字として`_`を採用しています。pixivでもタグの空白は`_`で代替されているので、この挙動が一番自然かと思います。
Closes #414.

タグの確定時に空白文字を置換する

---

app/MetadataResolver/MetadataResolver.php
app/MetadataResolver/TwitterResolver.php

fix #466 
Twitterの思いつく限りのサブドメインを正規化してOGPResolverに横流しするResolverを追加。

Twitterのサブドメイン対応用Resolverを追加

---

app/Http/Kernel.php
routes/api.php

Middleware Group内にいろいろ移したのはあまり関係がなくて、なぜかEncryptCookiesの前にStartSessionが走っていた。なんでだよ。

Stateful APIのMiddleware順序を調整

---

app/Http/Kernel.php
routes/api.php

throttle middlewareにはゲストアクセス時、ログイン時それぞれのレートリミットが書けると教えてもらったので、ゲスト時はcard APIへのアクセスを絞ることにした。
thanks hinaloe.

ゲストアクセス時のレートリミットを厳しめにする

---

app/MetadataResolver/CienResolver.php
tests/Unit/MetadataResolver/CienResolverTest.php
tests/fixture/Cien/test.html

いつのまにか `px-time` が廃止されてJWTが付与されるようになっていた。  
このPRでは、JWTをデコードしてその有効期限をメタデータの失効時刻として扱うように変更する。

Ci-en: JWTから有効期限を取得する

---

app/Services/MetadataResolveService.php

`http://shibafu528.info` とかを取得しようとするとHTMLが返ってきてrobots.txtパーサーが暴走してタイムアウトすることがあった。  
明らかな異常パターンを弾くための措置として、Content-Typeチェックを行うようにする。

robots.txt取得時、text/plain以外の応答は失敗扱いにする

---

.env.example
tests/Unit/MetadataResolver/CienResolverTest.php
tests/Unit/MetadataResolver/CreateMockedResolver.php
tests/Unit/MetadataResolver/DLsiteResolverTest.php
tests/Unit/MetadataResolver/DeviantArtResolverTest.php
tests/Unit/MetadataResolver/FC2ContentsResolverTest.php
tests/Unit/MetadataResolver/FantiaResolverTest.php
tests/Unit/MetadataResolver/FanzaResolverTest.php
tests/Unit/MetadataResolver/HentaiFoundryResolverTest.php
tests/Unit/MetadataResolver/IwaraResolverTest.php
tests/Unit/MetadataResolver/Kb10uyShortStoryServerResolverTest.php
tests/Unit/MetadataResolver/KomifloResolverTest.php
tests/Unit/MetadataResolver/NicoSeigaResolverTest.php
tests/Unit/MetadataResolver/NijieResolverTest.php
tests/Unit/MetadataResolver/PixivResolverTest.php
tests/Unit/MetadataResolver/PlurkResolverTest.php
tests/Unit/MetadataResolver/SteamResolverTest.php
tests/Unit/MetadataResolver/ToranoanaResolverTest.php
tests/Unit/MetadataResolver/XtubeResolverTest.php

fix #463
環境変数 `TEST_UPDATE_SNAPSHOT` を設定することで、実リクエストテストをする際にレスポンスをfixtureとして保存する処理を差し込むようにしました。
~ちょっとHTMLの浄化とかしたほうが良いかもしれないので、まだドラフトということでご意見募集中。~  
→ あんまり考えなくてもいいかなぁになってます。

Fixture updater

---

resources/assets/sass/_underline-tabs.scss
resources/assets/sass/app.scss
resources/assets/sass/components/_profile-mini.scss
resources/views/components/header-dropdown-menu.blade.php
resources/views/components/profile-mini.blade.php
resources/views/components/profile.blade.php
resources/views/layouts/base.blade.php
resources/views/user/base.blade.php

プロフィールページ内のタブおよびユーザー名あたりのデザインを変更。  
プロフィールページ内タブと内容が被っている部分については、アカウントメニュー内にリンクを置くだけにした。    
代わりに、お惣菜コーナーへのリンクを追加。

プロフィールページ内タブのデザイン変更とヘッダーナビゲーションの再編

---

Dockerfile

`https://getcomposer.org/installer` で得られるcomposerのバージョンが2.0系になったので、prestissimoをインストールしないようにする。  
今まで本当にありがとう……

thanks prestissimo, goodbye!

---

app/Ejaculation.php
app/Http/Controllers/Api/WebhookController.php
app/Http/Controllers/EjaculationController.php
app/Http/Controllers/UserController.php
app/Http/ViewComposers/ProfileStatsComposer.php
database/migrations/2020_11_08_005107_add_discard_elapsed_time_to_ejaculations.php
openapi.yaml
resources/assets/js/components/CheckinForm.tsx
resources/views/components/profile-stats.blade.php
resources/views/ejaculation/show.blade.php
resources/views/user/profile.blade.php

fix #332 
チェックインオプションとして「前回チェックインからの経過時間を記録しない」を追加します。
このオプションを有効にした場合、次のような効果があります。
* チェックインに経過時間が表示されなくなる。
* 概況欄の平均の計算対象が、このオプションを有効にしたチェックインから最新のチェックインまでになる。(直近30チェックイン内に存在する場合)
* 概況欄の最長・最短・合計の計算から除外される。
仕様検討にあたっては、Tissueへのチェックイン記録を再開する時にしか統計をリセットする実質的な意味は無いと捉え、そのようにオプションを配置することとしました。  
また、記録として使えなくなっているのは、利用を中断してから再開するまでの2点間のみであると考えたため、この区間のみを各種計算から除外するような形にしました。

「前回チェックインからの経過時間を記録しない」チェックインオプションの追加

---

resources/assets/sass/app.scss
resources/views/layouts/base.blade.php

ユーザーページでstatus alertを出した時に余白が無くて不恰好なのを修正

---

.circleci/config.yml

CIでカバレッジ取りに使用するXdebugのバージョンを落とす

---

resources/assets/js/components/TagInput.tsx

スマホから使っているとタグの入力を確定させずにチェックインボタンを押すことが多発したためです

タグ入力欄からフォーカスが外れた時、入力があるならタグとして確定させる

---

Dockerfile

Dockerを利用して開発環境をM1 Macで動作させるにあたって、jessieベースのイメージだとarmv8のビルドが提供されていなかった。  
phpイメージのベースディストリと合わせる形でアップグレードする。

Docker: nodeイメージのベースディストリをアップグレード

---

app/MetadataResolver/OGPParsePriority.php
app/MetadataResolver/OGPResolver.php
tests/Unit/MetadataResolver/OGPParsePriorityTest.php

内部APIとして欲しい的な要望があったので。
OGPResolver::parse() の第2引数として、タグの優先度を指定するためのオブジェクトを入力できるようにした。  
このオブジェクトは一般的には OGPParsePriority::preferTo() で生成する。全ての目的 (タイトルとか、詳細とか) で指定した優先度を使うという意味で、大抵はこれで事足りると思う。  
タイトルだけTwitter Cardsを優先するといったような指定が必要な場合は、コンストラクタを使えば目的ごとに別々の優先度を指定することができる。

OGPResolver::parse() にタグ優先度を指定できるようにする

---

resources/assets/js/components/MetadataPreview.tsx

オカズリンクから表示したタグ候補が無限にクリックできたので修正しました。  
Vue.js時代はこんなん無かったと思うので、たぶんReactに移行した時にデグレした。

既に追加されているタグを候補から追加できるバグの修正

---

app/Http/Controllers/UserController.php
resources/assets/sass/app.scss
resources/assets/sass/components/_stat-table.scss
resources/views/user/stats/components/used-tags.blade.php
resources/views/user/stats/index.blade.php
resources/views/user/stats/monthly.blade.php
resources/views/user/stats/yearly.blade.php

グラフページに、指定期間中に自分がよく使ったタグ、それに加えてオカズに付いていたタグも考慮した集計を追加します。  
目的としては、ある期間によく使ったオカズの傾向を知るための1資料として使えるかなと思ってのことです。

よく使っているタグを統計情報として表示

---

.circleci/config.yml
composer.lock

[PHPUnit 8.5.10](https://github.com/sebastianbergmann/phpunit/blob/83491f4d19d18c868829a013f0ee0839dd53c684/ChangeLog-8.5.md#8510---2020-11-27) でXdebug 3.0対応が入ったらしいのでアップデートする。  
これでCircleCIのconfigのバージョン固定を一旦外せるのと、ローカル環境のXdebugを上げても大丈夫になる。

PHPUnit 8.5.13

---

resources/assets/js/app.ts
resources/assets/sass/components/_link-card.scss
resources/views/components/link-card.blade.php

#270 で導入された過激なオカズを隠す機能ですが、実際に使われているのを見るとぼかしを解除するまでそれが何であるかが全く予想できないと感じたので、画像にだけ適用するように変更するPRです。
自分はこのほうが良いとおもうのですが、反対や他の意見があれば伺いたいです。

センシティブフラグのぼかしを画像にだけ適用するように変更

---

.circleci/config.yml

昔やったハックが不要になってそうなので外す。30秒くらい短縮できる。

CI: node 12.16.3の固定をやめてみる

---

resources/assets/js/components/TagInput.tsx

Reactに移行する際に #184 の対応が適切に移植されていなかった。
- ArchLinux / Chromium 87.0.4280.141 / fcitx-skk
- macOS 10.15.7 / Chrome 87.0.4280.141 / AquaSKK
- macOS 10.15.7 / Safari 14.0.2 / AquaSKK
で確認済。

macOSにおけるタグ確定処理のデグレード修正

---

app/MetadataResolver/MetadataResolver.php
app/MetadataResolver/NarouResolver.php
tests/Unit/MetadataResolver/NarouResolverTest.php
tests/fixture/Narou/novel.html
tests/fixture/Narou/novel_longdescription.html

とデグレ
close #603 
- 連載ページ（`novel18.syosetu.com/n0000aa/`）以外でも作者名とあらすじが取れるようになりました。
- データを小説情報（`novel18.syosetu.com/novelview/infotop/ncode/n0000aa/`）をからパースするようになりました。どのURLからでもタグ（キーワード）とあらすじを取得できます。
- ![image](https://user-images.githubusercontent.com/3516343/105745284-75667180-5f81-11eb-955e-485d13f8b29e.png)
- 逆に単話ページ（`novel18.syosetu.com/n0000aa/1`）のリンクを貼っても単話のタイトルや本文（もともと対応してなかったが）が取れなくなりました。
- これは小説情報ページにタイトルの一覧が載っていないのと、MetadataResolverは1回のメタデータ取得に1つのリクエストしか送れないためです。（正確には送れるがテストができない）
- この点を問題と捉えるか否かは実際にこのリゾルバを使っているユーザーに聞きたいです。

NarouResolverの修正と改善

---

resources/views/admin/info/index.blade.php
resources/views/search/relatedTag.blade.php

fix #630 
Issueにて指摘された箇所は #99 で削除したはずの古いページャー実装が使われていたため、大半のページで使用されている現行のものに置き換えました。  
ついでに、管理ページにも残っていたので置き換えておきました。こっちは誰も使わないけど。

古い省略表示の無いページャーを現行のものに置換

---

composer.json

laravel-ide-helperのコマンドが一生覚えられないので、composer.jsonに書いておくことにしました。

ide-helperのコマンドをまとめて実行するscriptを追加

---

Dockerfile

laravel-mix 6.xはnode 12以上じゃないと使えないっぽかった。ローカルの14.xで実行してたので気づかなかった……
どうせまた忘れるので最新版まで上げる。

Docker: node 16にアップデート

---

app/Http/Controllers/Api/CardController.php
app/Listeners/LinkCollector.php

DisallowedByProviderExceptionがSentryに送られすぎてレートリミットにかかった。
改めて考えてみると、これは管理者側でブロックしている場合のDeniedHostExceptionと全く同じ扱いでいいはずで、そうしておけばSentryに送られることもない。ということで、そのようにする。

DisallowedByProviderExceptionは403扱いで握り潰す

---

tests/Unit/MetadataResolver/FanzaResolverTest.php

#742 のCIで発覚した問題への対応。
libxml2のバージョンによってXMLの解釈が異なる場合、より新しいlibxml2の結果を正とする。

libxml2のバージョンによって解釈が異なるテストのアサーション修正

---

app/Ejaculation.php
app/Http/Controllers/UserController.php

fix #759 
いいね一覧のクエリで whereHas を使うのをやめて、相当するJOINを手書きしました。これで相関サブクエリが原因の速度低下が改善されます。  
また、ソート条件を created_at から id に変更することで、indexが使用されるようにします。
```sql
-- ページネーション用のカウント
select count(*) as aggregate
from "likes"
where "likes"."user_id" = ?
and "likes"."user_id" is not null
and exists(select *
from "ejaculations"
left join (select "ejaculations"."id" as "ejaculation_id", count(*) as is_removed_by_tag_filter
from "ejaculations"
inner join "related_ejaculation_tags"
on "ejaculations"."id" = "related_ejaculation_tags"."ejaculation_id"
inner join "tags" on "related_ejaculation_tags"."tag_id" = "tags"."id"
inner join "tag_filters" on "tags"."normalized_name" =
"tag_filters"."normalized_tag_name" and
("tag_filters"."user_id" = ? and "tag_filters"."mode" = 2)
group by "ejaculations"."id") as …
```

いいね一覧のSQLを高速化

---

app/Http/Controllers/Api/CheckinController.php
app/Http/Controllers/EjaculationController.php
app/Http/Controllers/UserController.php
resources/assets/js/tissue.ts
resources/views/components/delete-checkin-modal.blade.php
resources/views/components/ejaculation.blade.php
resources/views/ejaculation/show.blade.php
resources/views/home.blade.php
resources/views/search/index.blade.php
resources/views/timeline/public.blade.php
resources/views/user/likes.blade.php
resources/views/user/profile.blade.php
routes/api.php
routes/web.php

今までチェックイン表示用のコンポーネントはバラバラに実装されていて、一部のみejaculation.blade.phpに統合されている状態でしたが、ここ1年では実装をバラバラにしておくメリットも薄いと感じたため統合を試みました。
また、今までのチェックイン削除はForm POSTを使っていましたが、Ajaxでの処理に変更しました。  
あらゆる画面で削除が押せるようになり、削除後に一律でプロフィールページにリダイレクトするのが微妙になったためです。  
`/checkin/:id` の画面だけは今まで通りっぽい振る舞いで、他の画面は一覧系なのでリスト上からチェックインを消すような処理を仕込みました。

チェックイン表示用テンプレートの統合

---

app/MetadataResolver/CienResolver.php
tests/Unit/MetadataResolver/CienResolverTest.php
tests/fixture/Cien/test.html
tests/fixture/Cien/testWithNoPostImage.html

バナー抽出機能の削除
- 投稿に画像がある場合、OGPの画像にそれが使われるようになっていたのでそのままにする
- image-800.jpgなのでおそらく最大800px幅
JWTからpx-timeに差し戻し
- いつの間にか有効期限に関するパラメータがpx-timeに戻っていた
- 実質的に #530 の差し戻し
- [検索結果](https://shikorism.net/search/checkin?q=url%3Aci-en)が死んでるのが直る……はず

CienResolver: バナー抽出機能の削除・JWTからpx-timeに差し戻し・テストの修正

---

app/Http/Controllers/UserController.php
resources/assets/sass/app.scss
resources/views/user/stats/yearly.blade.php

今年よく使ったオカズを振り返る枠を年間統計ページに追加します。  
2回以上使っているオカズを10位まで並べます。
年末企画として直接本番に上げたいです。(なので、master宛)

今年よく使ったオカズのランキングを年間統計ページに追加

---

resources/views/components/ejaculation.blade.php
resources/views/ejaculation/show.blade.php

投稿ソースを詳細画面で小さく表示するように変更

---

app/Utilities/Formatter.php
tests/Unit/Utilities/FormatterTest.php

Format::formatInterval の日数部をカンマ区切りでフォーマットする

---

app/Http/ViewComposers/ProfileStatsComposer.php
resources/assets/sass/app.scss
resources/assets/sass/components/_profile-stats.scss
resources/views/components/profile-stats.blade.php

fix #884 
今まで全部の項目が4文字でなんとなく揃っていたのが崩れたので、レイアウトも変更。

概況欄に中央値を追加

---

composer.json
composer.lock

[symfony/dom-crawler 4.4.38](https://github.com/symfony/dom-crawler/releases/tag/v4.4.38) で文字コードの判定が変わってテストが落ちた。これを書いている時点のdevelopのCIが通ってるのはよくわからん。
明示的に文字コードを指定してロードさせる方法はありそうな気がするが、下げたところで何も困らないので下げる。

Downgrade symfony/dom-crawler 4.4.42 to 4.4.37

---

dist/php.d/99-xdebug.ini

IntelliJでデバッグしようとしたら全く動かなくて頭を抱えたけど、単に2.x→3.xの設定マイグレーションをやれということだった。
https://xdebug.org/docs/upgrade_guide/ja

Docker: xdebug 3になってからデバッグ用設定が動作していなかったのを修正

---

resources/assets/js/user/collection.tsx

fix #936 
このためにサーバーサイドで note_html というプロパティを内部利用目的で出力していたのに、使うのを忘れていた。

CollectionItemのノート内URLをリンク化し、改行も反映した

---

app/MetadataResolver/PixivResolver.php

コードの通り、非ログイン時に表示できない（R18やセンシティブが設定されている）投稿だとurlが出てこなくなったので解決できてなかったが、userIllustsには入っていることがわかったのでそれを使うようにして修正
指定した投稿の情報が必ずしもuserIllustsに含まれているかは解らないがいくつか試した限りでは取れていそうだった
問題が起きても空文字列になるだけなら困ることもなさそう（そうするにはtry-catchが必要？）
---
56ffa1b で直したcustom-thumbは詳細不明。いくつかの投稿で使われていた
例
- `https://www.pixiv.net/artworks/78644857`
- `https://www.pixiv.net/artworks/77561578`

PixivResolver: 画像取れない問題を修正

---

app/MetadataResolver/MelonbooksResolver.php
tests/Unit/MetadataResolver/MelonbooksResolverTest.php
tests/fixture/Melonbooks/testCensored.html
tests/fixture/Melonbooks/testUncensored.html

fix #903, #1009
- ページタイトルのフォーマットが変わってパースに失敗していたので、正規表現を修正しました。
- サイトリニューアルでDOM構造も変わっていて作品詳細が取れなくなっていたので、XPathを修正しました。かなりナイーブなのですぐ壊れそうな気がします。
- テストがなかったので、簡単にスナップショットテストを入れておきました。

MelonbooksResolver: ページタイトルフォーマット・DOM構造変更に追従

---

docker/production/bin/tissue-php-entrypoint
docker/production/php.dockerfile

fix #1110 
tissue-phpの起動時に `config:cache` と `view:cache` を実行するようにしました。
コンテナビルド時にやってしまうと必要な環境変数が読めない (config)、出力先に意味が無い (view) などの問題があるため、たぶんここにしか入れられないはず?

docker/production: tissue-phpの起動時にキャッシュを作成する

---

.circleci/config.yml
app/Collection.php
app/CollectionItem.php
app/Http/Controllers/Api/UserCollectionController.php
app/Http/Controllers/Api/V1/CollectionController.php
app/Http/Controllers/Api/V1/CollectionItemController.php
app/Http/Controllers/Api/V1/UserCollectionController.php
database/factories/CollectionFactory.php
database/factories/CollectionItemFactory.php
openapi.yaml
package.json
routes/api.php
tests/Feature/Api/V1/CollectionItemTest.php
tests/Feature/Api/V1/CollectionTest.php
tests/Feature/Api/V1/UserCollectionTest.php
yarn.lock

この機能を愛用している方が一部にいるので、応用してもらえるように公開API化を検討しています。
現状の非公開APIの実装でほぼ十分なので、少しだけ手直しして公開APIに移動させます。
- 認証必須
- 自分のコレクションをユーザー名指定省略で取るAPIは無い
- DELETEがべき等ではない
- べき等にするのは仕様検討[^1]も実装[^2]も面倒なので、今後は削除済みリソースは404返す方針に揃えるかも
[^1]: 他人の非公開リソースへの操作を404で返すと定義した場合、それにDELETEを送ったら消せないはずなのに204になるの? でも、404を返したら存在することが分かるよね? とか、そういう悩み
[^2]: ルートモデル結合が使えなくなる

Collection APIを公開API化

---

app/Http/Controllers/Api/V1/UserCheckinController.php
openapi.yaml
tests/Feature/Api/V1/UserCheckinTest.php

WebUIの `/user/{username}/okazu` 相当のデータを取り出すためのオプションを追加しました。

チェックイン一覧API オカズリンクを含むチェックインのみ取得するオプションを追加

---

app/Http/Controllers/Api/UserCollectionController.php

公開API `GET /api/v1/users/{user}/collections` と挙動を揃える。
こうすることで、フロントエンドで一番若いIDのコレクションを表示するつもりが適当なコレクションを表示してしまっているバグも直る。

GET /api/users/{user}/collections の結果をID順にソートする

---

app/Ejaculation.php

チェックインのオカズリンクを更新した時にnormalized_linkも更新する

---

app/Console/Commands/CleanLock.php
app/Console/Kernel.php
app/Exceptions/GlobalLockException.php
app/MetadataResolver/CienResolver.php
app/MetadataResolver/FxTwitterResolver.php
app/MetadataResolver/MetadataResolver.php
app/Providers/AppServiceProvider.php
app/Services/MetadataResolveService.php
app/Utilities/ApplyProviderPolicyMiddleware.php
app/Utilities/GlobalLock.php
app/Utilities/URLUtility.php
compose.yaml
docker/production/sample/compose.yaml
storage/global_lock/.gitignore
tests/Unit/Services/MetadataResolverServiceTest.php
tests/Unit/Utilities/URLUtilityTest.php

fxtwitter.com を経由してXのポストからメタデータを取得する実装を追加しました。
FxTwitterResolverを追加したのはいいのですが、これだけだとダメでした。
既存実装ではメタデータ解決の入力URLに書かれているホストに対してrobots.txtチェックを行っていますが、https://x.com/robots.txt ではほとんどのbotが拒否されているからです。
この制御の目的は
- 同時アクセスが発生しないようにする
- robots.txtの解析を行い拒否されている場合にメタデータの取得処理を行わない
ことですが (#468 より) 、実際にHTTPリクエストを行う先に対してチェックするほうがより妥当と言えます。  
(x.comにアクセスしていないのに、そこのrobots.txtに従う道理は無い)
そのため、制御を行う場所をMetadataResolverの実行前から、MetadataResolverが使うGuzzleのmiddlewareスタック内に移動させました。

FxTwitterResolverの追加 & 同時アクセス制御・ポリシー制御単位をResolver内のHTTPリクエスト毎に変更

---

package.json
resources/assets/js/components/MetadataPreview.tsx
resources/assets/js/components/TagInput.tsx
resources/assets/js/user/collection.tsx
resources/assets/sass/app.scss
resources/views/components/ejaculation.blade.php
resources/views/search/collection.blade.php
yarn.lock

Tabler Icons 3.6がリリースされて、tag-filledがマージされたっぽいので使うことにしました。

Tabler Icons 3.6, タグ周りのUI差し戻し

---

app/Collection.php
app/Http/Controllers/Api/V1/CollectionItemController.php
app/Http/Resources/CollectionResource.php
resources/assets/js/components/collections/AddToCollectionButton.tsx
resources/assets/js/components/collections/CollectionSelectModal.tsx
resources/assets/js/components/collections/SortKeySelect.tsx
resources/assets/js/components/collections/search.ts
resources/assets/js/user/collections.tsx

fix #1197 
- コレクション作成数の上限を 100 → 500 に緩和しました。
- 検索ボックスを追加しました。名前で絞り込みができます。
- ソート順序のバリエーションを増やしました。
- スマホ表示の場合、コレクション一覧を折り畳むようにしました。
- 表示を更新日時の降順で、先頭5件に制限しました。
- 6件目以降を選択するためのモーダルを追加しました。

Collectionの最大数緩和とUI改善

---

resources/assets/sass/tissue.css
resources/views/home.blade.php

お知らせ欄は、当初はメインカラムにあったのですが、その後[サイドカラムに移動](https://github.com/shikorism/tissue/pull/89)しています。  
これはメインコンテンツの表示量を稼ぐための変更だったのですが、PCの事しか考えられておらず、スマホでは依然邪魔な状態が続いていました。
このPRでは、スマホ向けの表示でもお知らせ欄が表示領域を占有しすぎないよう、表示位置とデザインを変更しました。
- 「ピン留め」は管理者都合の属性であり、閲覧者には特に意味のある情報ではないため削除しました。
- 過去のお知らせをわざわざ見る人はそんなに居ないので、一覧画面へのリンクは削除しました。一応、いずれかのお知らせを開いてからパンくずリストを経由すれば開ける。

サイトトップのお知らせ表示を小さめにした

---

.circleci/config.yml
docker/development/web.dockerfile
docker/production/foundation.dockerfile
package.json

前回: #714 
ついでにcorepack enableをDockerfile内に仕込んだり、package.jsonに `packageManager` を書き込んだりした。

Docker: node 22にアップデート

---

resources/assets/js/app.ts
resources/assets/js/setting/deactivate.ts
resources/assets/js/setting/filter/tags.ts
resources/assets/js/setting/import.ts
resources/assets/js/setting/privacy.ts
resources/assets/js/setting/tokens.ts
resources/assets/js/setting/webhooks.ts
resources/assets/js/tissue.ts
webpack.mix.js

大昔の自分が便利だと思って入れたのだろうけど、今となっては便利さよりも余計な驚きという気持ちが強い。
mix.autoloadで注入するのではなく、普通にimportするようにする。

jQueryを明示的にimportする

---

app/Http/Controllers/Api/V1/RecentTagsController.php
app/Http/Controllers/Api/V1/UserStats/MostlyUsedCheckinTags.php
resources/assets/js/@types/api.d.ts
resources/assets/js/api.ts
resources/assets/js/checkin.tsx
resources/assets/js/components/CheckinForm.tsx
resources/assets/js/components/FavoriteTags.tsx
resources/assets/sass/app.scss
routes/api.php

@eai04191 が作成した https://userscript-graveyard.vercel.app/#/userscript/tissue/favorite-tags の仕様をベースとして、だいたいそのまま本体に組み込むPRです。
`GET /api/v1/users/{name}/stats/tags` から取得できる、ログインユーザーが最も使用したタグを列挙。
期間指定をせずに呼び出しているので全期間対象。集計が重くなるだけなので、直近1年かもっと短めに縛ってもいいかもしれない。
元ネタだと最近のオカズリンク付きチェックインからスクレイピングしていたけど、オカズリンクがなくてもタグは書けるのでチェックイン日時降順のトップ20に設定されているタグを列挙するようにした。
全て表示するとキリがないので、適当に切り捨て。全表示するボタンを付けてもいいかも。

よく使うタグ・最近使ったタグをチェックインフォームに表示

---

app/Providers/AppServiceProvider.php

`per_page`などのパラメーターを付与した状態でREST APIを呼び出した際、レスポンスヘッダー(Linkヘッダー)へ出力されるURLから呼び出し時に付与したパラメーターが欠落した状態で出力されていました。
本修正では、呼び出し時に付与したクエリーパラメーターを引き継ぐよう修正を行っています。

REST API呼び出し時に指定したクエリーパラメーターがLinkヘッダーへ出力されるURLから欠落している問題を修正

---

app/MetadataResolver/FantiaResolver.php

Fantia APIに `X-Requested-With` ヘッダーが必要になっていたため、リクエストを修正しました。
このヘッダーがないと、HTTP 422 で以下のようなレスポンスが返ってきてしまいます。
```json
{"error_text":"システムエラー"}
```

FantiaResolver: リクエストに X-Requested-With ヘッダーを付与

---

.circleci/config.yml
README.md
app/MetadataResolver/ActivityPubResolver.php
app/MetadataResolver/DLsiteResolver.php
app/MetadataResolver/MelonbooksResolver.php
app/MetadataResolver/NarouResolver.php
app/MetadataResolver/OGPResolver.php
app/MetadataResolver/ToranoanaResolver.php
app/Utilities/Formatter.php
composer.json
composer.lock
docker/development/web.dockerfile
docker/production/config/php.ini
docker/production/foundation.dockerfile
docker/production/php.dockerfile

[PHP 8.1以降はサポートが伸びた](https://wiki.php.net/rfc/release_cycle_update)ので、まだあと1年は猶予がある。
ただ、PHP 8.2まで上げておかないとLaravelを現在サポート中の最新版 (Laravel 11) まで一気に上げることができないので、結局さっさと上げないといけなかった。

DockerfileおよびCI環境をPHP 8.2にアップデート

---

vite.config.js

通報理由の管理画面が開発環境以外で開けないバグを修正

---

app/MetadataResolver/NarouResolver.php
tests/Unit/MetadataResolver/NarouResolverTest.php
tests/fixture/Narou/testFeaturesInKeyword.html

fix #1323
[作品に含まれる要素](https://syosetu.com/helpcenter/helppage/helppageid/57)によって設定されたキーワードが `&nbsp;` 区切りで出力されていて、うまくタグ分割できていなかったのを修正しました。

NarouResolver: 作品に含まれる要素のキーワードに含まれるnbspを除去

---

app/MetadataResolver/DLsiteResolver.php
tests/Unit/MetadataResolver/DLsiteResolverTest.php
tests/fixture/DLsite/testGirlsCoupling.html

fix #1322 
作品情報にカップリング設定が含まれているとそれだけがタグとして扱われてしまい、ジャンルがタグとして抽出されなくなるバグを修正しました。
おそらく `div.main_genre > a` はいずれもタグとして抽出して良いだろうという想定で実装していますが、余計なメタデータが含まれてしまう可能性がありましたら教えてください。

DLsiteResolver: カップリング設定がある場合にジャンルがタグ抽出できないバグの修正

---

app/Utilities/ApplyProviderPolicyMiddleware.php

#1363 のCarbon v3更新による不具合。
- `sleep()` は整数しか受け付けないので、`diffInSeconds()` の戻り値を整数にキャストしてから処理するようにした
- 第2引数はv3でfalseがデフォルトになったので消した

メタデータ取得時、時々 sleep() にfloatが渡されてエラーになるのを修正

---

app/User.php

#1363 のCarbon v3更新による不具合。
公開API `GET /api/v1/me`, `GET /api/v1/users/{user}` のレスポンス `checkin_summary.current_session_elapsed` が、バージョンアップ以降意図せず浮動小数点数になっていた。
ここの型を変えるつもりはなかったので、バージョンアップ前と同様に整数で出力されるようにする。

GET /api/v1/me, GET /api/v1/users/{user} の checkin_summary.current_session_elapsed の型を整数に修正

---

app/Http/Requests/EjaculationReportRequest.php

このコードの意図は「violated_ruleがother以外だったら、選択されたviolated_ruleが実在することを確認」だったはず。
なぜか `comment` を第1引数に書いてしまっていて `select count(*) as aggregate from "rules" where "id" = :comment`  みたいなSQLが発行されて死んでいた。

「その他」以外の理由で詳細付きの報告をすると500エラーになるバグを修正

---

app/Http/Controllers/UserController.php
resources/assets/js/user/stats.ts
resources/views/user/stats/yearly.blade.php

年間グラフページに「去年のデータも表示」というスイッチを追加し、オンにしたら前年分のデータも併せて表示する機能を追加しました。  
任意の年と比較できたほうが便利だと思うけど、とりあえずあったら面白いかなの精神で実装してみました。

年間グラフに「去年のデータも表示」オプションを追加

---

app/Http/Controllers/UserController.php
tests/Unit/Http/Controllers/UserControllerTest.php

楽しく本アプリケーションを利用しております、いつもありがとうございます！
JST00:00から09:00の間にプロフィール画面のShikontributionsを閲覧すると、日付が実際にチェックインを行った日付から1日ずれて表示されます。
これは
- `Carbon::createFromFormat` に年月日のみ渡した場合、時分以降の値は現時刻が用いられる
- たとえば、2025/02/14 01:23 JSTに2025/01/14のチェックイン記録を参照すると、`createFromFormat('Y/m/d', '2025/01/14')`は2025/01/14 **01:23 JST**のインスタンスを生成する
- これがそのまま`count-by-day`にUNIX時間1736785380として渡され、フロントエンドがこのタイムスタンプを解釈する
- 正確には未検証ですが、CalHeatmapがタイムスタンプの解釈にあたってタイムゾーンを無視してUTCにおける日付を参照している気がする
- 前項の例に従えば、CalHeatmapはUNIX時間1736785380を2025/01/13 16:23 UTCとして解釈する
- この日付部分2025/01/13を用いてヒートマップが描画されるので、意図した2025/01/14から日付が1日ずれる（JST09:00以降はJSTの日付とUTCの日付は一致するので問題なし）
という要因によるものだと思われます。
これを修正する実装の案になります。
日付を示すタイムスタンプを生成する際、現時刻によらずUTC 00:00に揃えることで齟齬をなくすよう試みています。
作法に不整合があれば、指摘いただければ幸いです。

Shikontributions: JST00:00から09:00の間に閲覧すると、日付が1日ずれるのを修正

---

package.json
yarn.lock

#1403 のCIがコケている理由を確認していたら、どうやらVite 5.4.12, 6.0.9で導入された変更とlaravel-vite-pluginの相性が悪いようだった。
laravel-vite-plugin側では最新版で修正されているので、更新すればOK。ただし、現在のlaravel-vite-pluginはVite 6.x用なので、Viteも更新。

Vite 6.2.2, laravel-vite-plugin 1.2.0

---

resources/assets/js/components/MetadataPreview.tsx

Sassで `&` を使ってprefixを書くのをサボるのはやめたほうがいいと思いました。grepに引っかからん。

タグ候補リストのCSSクラス名の間違いを修正

---

resources/assets/js/components/CheckinForm.tsx

フロントでのオンタイムバリデーションはしてない
- #264
- 送信する前の文字列チェックは未実施（他のフォームでもやってないと見受けられるため）
- いいえ
- no
- no

チェックイン時のノート入力欄で残り入力可能文字数をカウントする

---

app/MetadataResolver/FanzaResolver.php
tests/Unit/MetadataResolver/FanzaResolverTest.php

タグ取得のセレクター、なんか微妙だなぁと思うのだけどパッと直すならこれくらいしか思いつかなかった。

FanzaResolver: PCゲームのタイトル・タグ取得処理を修正

---

app/Utilities/Formatter.php
tests/Unit/Utilities/FormatterTest.php

#836 で問題になっていたpreg_replace()の後段の処理でクエリが再パースされているので、Tissue全体としては単純文字列置換に差し替えても問題がないのではないかと思います。用例さえあればテスト増やして信頼性を上げられると思うので、よしなに願います。

normalizeUrl()がUTF-8以外を受け取った時にエラー落ちしていた不具合への対応

---

app/Services/CheckinCsvExporter.php
tests/Unit/Services/CheckinCsvExporterTest.php

https://github.com/shikorism/tissue/issues/1360 で指摘されていた不具合の対応。
エクスポート時の処理に`preg_replace()`を噛ませたので、csv以外のデータに変更はなし。

CSVエクスポート時のノート内改行をCRLFに統一する

---

.circleci/config.yml
.env.testing
CHANGELOG_FOR_DEV.md
README.md
compose.yaml
docker/development/init-test-db.sql

fix #734 
以下の対応を行い、ユニットテスト実行時に専用のデータベースが使われるようにしました。これで `composer test` を実行したら全てのデータが飛ぶことはなくなるはず……！
- env_fileをcompose.yamlで指定するのをやめて、`APP_ENV=testing` の時に `.env.testing` が使われるようにした
- Docker Compose環境でのテスト実行を想定した `.env.testing` を追加
- DBコンテナ初期化時にテスト用のデータベースを作成するようにした

ローカルでのテスト実行に専用のデータベースを使用する

---

app/Http/Controllers/Api/V1/UserCheckinController.php
openapi.yaml
tests/Feature/Api/V1/UserCheckinTest.php

将来的にチェックインの月単位ビュー (Twilogやnotestockのようなイメージ) を実装したいなと思っての機能追加です。
- since, until
- 既存のstats APIと同じような仕様です。チェックイン日時の範囲指定。
- order
- チェックイン日時の並び順です。デフォルトは従来同様の降順。

API: GET /api/v1/users/:username/checkins order,since,untilパラメータ追加

---

compose.yaml

開発環境用のcompose.yamlにそれは要らんやろと今更思ったので消すことにした。
SNSでTissueの開発環境が勝手に起動するという悲鳴を上げてる人もいたことだし。

Docker: restart alwaysを削除

---

.devcontainer/compose.yaml
compose.yaml

Codespacesで遊んでいたらwebコンテナのnode_modulesが空のままで、git commitしようとしたらhuskyがなくて困った。
多分、frontコンテナと共有しておいたほうが都合が良い。

docker: web/frontコンテナ間でnode_modulesを共有
